### ISSUE TITLE
How to do mark primary panels

### ISSUE THREAD

**Issue by mohsinulhaq** [bvaughn/react-resizable-panels#102]
I have a use case where one or more of the panels are primary content panel(s), i.e., resizing/collapsing any other panel distributes the size among the primary panel(s) only, leaving the panels around the resized/collapsed panel unchanged.

I was kinda able to get this done by changing this source here: https://github.com/bvaughn/react-resizable-panels/blob/main/packages/react-resizable-panels/src/utils/group.ts#L146

But I was wondering if there was a cleaner way without changing the lib code.

**Comment by bvaughn** [comment]
I can't think of a way to support that use case with the current API, and I don't think it's something I want to support given other trade offs (mostly time and complexity). Sorry 🙇🏼
