### ISSUE TITLE
Provide collapse direction support

### ISSUE THREAD

**Issue by mohsinulhaq** [bvaughn/react-resizable-panels#103]
Currently, the panels collapse towards the left, making the panel to the right larger. I would like to have the option to provide the collapse direction myself to the panels. Is that possible from outside the library?

**Comment by bvaughn** [comment]
I assume you are describing a 3 panel (or more) situation where you are collapsing the middle panel?

So something like this:
```
|••L••|••M••|••R••|
```

To something like this:
```
|••L••||••••R••••|
```

But you would prefer this instead:```
|••••L••••||••R••|
```

> Is that possible from outside the library?

Assuming I'm right about the scenario I described above, I believe you would want to do something like this:
```js
// Use the onResize prop for Left and Middle panels to store their current sizes in state or a ref
// Then transfer the size of the middle panel to the left panel like so:
leftPanelRef.current.resize(leftPercentage + middlePercentage);
middlePanelRef.current.resize(0);
```

**Comment by mohsinulhaq** [comment]
@bvaughn that would require outside app to attach refs and based on the collapse target, figure out the left and the right panels.
Doable, but I was wondering if you would be interested in providing a collapse API like :
```tsx
  void collapse(direction: 'start' | 'end');
```

**Comment by bvaughn** [comment]
If you would like to post a PR, I’ll record it. It’s not a feature I have the time/interest to build though.

**Comment by ethanyou725** [comment]
> @bvaughn that would require outside app to attach refs and based on the collapse target, figure out the left and the right panels. Doable, but I was wondering if you would be interested in providing a collapse API like :
> 
> ```tsx
>   void collapse(direction: 'start' | 'end');
> ```

currently both `collapse` and `expand` api on `Panel` component will affect the current the the next one, so if `collapse` accept direction as param, `expand` should has the same ability.

**Comment by mohsinulhaq** [comment]
> expand should has the same ability.
Definitely!

**Comment by ethanyou725** [comment]
https://github.com/bvaughn/react-resizable-panels/pull/107 
I tried resolve this and created a PR

**Comment by bvaughn** [comment]
After thinking on it a little bit, I've decided that I don't think I want to add this functionality to the library. I understand the use case, but I think the "before" and "after" API is a bit awkward and I think I'd prefer to just stick with the current constraints.

I hope you'll understand 🙇🏼  and you are definitely welcome to fork this module if you'd prefer to build on top of this proposal for your own application.
