### ISSUE TITLE
Library depends of `useId` which is only available in React v18  

### ISSUE THREAD

**Issue by tim-field** [bvaughn/react-resizable-panels#104]
Which is fine I guess, but the package.json doesn't specify react v18 as a requirement :)

**Comment by bvaughn** [comment]
It’s not a requirement. This library falls back to non useId

**Comment by tim-field** [comment]
hmm wasn't compiling for me with react v17

**Comment by bvaughn** [comment]
Can’t really help with that without a repro, sorry. I’ve tested this with react 16 and 17 on code sandbox though

also see
https://github.com/bvaughn/react-resizable-panels/issues/82#issuecomment-1380980049

**Comment by bvaughn** [comment]
Cleaning up stale issues.

**Comment by bvaughn** [comment]
Fixed in 0.0.38

**Comment by ParseDark** [comment]
> 0.0.38

Thanks. Bro
