### ISSUE TITLE
Can't expand both panels at the same time once both are collapsed

### ISSUE THREAD

**Issue by mohsinulhaq** [bvaughn/react-resizable-panels#106]
https://codesandbox.io/s/react-resizable-panels-forked-jhttme?file=/src/App.js

In this sandbox, I am imperatively expanding and collapsing the panels.
Suppose you collapse both the left panel and the right panel. Only one panel is visible now. You will find that there is no way to keep both of them expanded at the same time now.

**Comment by bvaughn** [comment]
This seems to me like it's working as I would expect. There are only two panels in the group. Collapsing one requires expanding the other. If you want both to be collapsible at the same time, the group would need a third panel.

I'm going to close this as "working as designed" for now.

**Comment by mohsinulhaq** [comment]
@bvaughn
>  If you want both to be collapsible at the same time

No, I guess I was not clear enough. I meant once you press the collapse buttons for both panels one after another, there's no way to get back to the original state of both panels being expanded at the same time.

**Comment by bvaughn** [comment]
There is though.

1. Drag a resize handle, or
2. Use the resize() API

**Comment by mohsinulhaq** [comment]
@bvaughn but i’m only talking about expand/collapse API from which this issue stems.

In my use case, I have a lot of panels with toggle button added in, and the user was really annoyed that once they collapsed the last two panels, they couldn’t get back to seeing both panels together again.

**Comment by bvaughn** [comment]
I understand what you are talking about, but that’s how those apis work. Expand returns the panel to its most recent size before collapsing. Given a two-panel group, it just doesn’t make sense to collapse both panels in the first place I think.

Maybe you could avoid this but changing the button behavior to call expand() on the other panel before calling collapse() on the target panel to avoid both being collapsed at the same time.

Please remember that I’m not charging anything for this library (or from troubleshooting issues). ☺️

**Comment by mohsinulhaq** [comment]
> changing the button behavior to call expand() on the other panel before calling collapse()
@bvaughn that's a good idea :)
> remember that I’m not charging anything for this library
My bad. I forget my place🙇. It's just that I have spent quite some time in your codebase. It's so concise yet so powerful.
So as soon as I discover some use case not covered by the source, I'm either trying to add the change myself (albeit introducing other bugs along with it), or I am raising them to you for discussion. So thanks for your prompt responses. Much appreciated. :)

**Comment by bvaughn** [comment]
No worries 😄  I'm glad the library has been helpful for you! Hope my suggested work around helps you in this situation.
