### ISSUE TITLE
Best way to implement "expand" into particular panel

### ISSUE THREAD

**Issue by lucasmrl** [bvaughn/react-resizable-panels#110]
Hey @bvaughn!
First, thanks for the library. I found it just in time for a short experiment. :)
What would be the best approach to add a "expand" functionality to a nested panel?

In the image below, I want to have a button that will expand the "red" component to occupy all/almost all the width and height available:
<img width="877" alt="image" src="https://user-images.githubusercontent.com/44297238/222571877-9839ceab-3770-4964-9400-53d6a7124509.png">

Best,

**Comment by bvaughn** [comment]
You'll need two refs:
1) One for the right most panel in the horizontal group
2) One for the bottom panel in the vertical group

Then you'll just need to call: `expand` on both of them.

**Comment by lucasmrl** [comment]
Perfect, will give it a try! Thank you!
