### ISSUE TITLE
[Bug] Unhandled Thrown Error!

### ISSUE THREAD

**Issue by geobde** [bvaughn/react-resizable-panels#112]
Just tried to play with demo examples and throw this error:

Unhandled Thrown Error!
`Failed to fetch dynamically imported module: https://react-resizable-panels.vercel.app/dist.369669ea.js`

**Comment by bvaughn** [comment]
Works fine for me 🤷🏼‍♂️

**Comment by geobde** [comment]
maybe it was local issue sorry for that

**Comment by bvaughn** [comment]
No worries :)
