### ISSUE TITLE
Panels do not consistently collapse when they are up against the edge of the viewport

### ISSUE THREAD

**Issue by incompl** [bvaughn/react-resizable-panels#116]
Here is a codesandbox that reproduces the issue: https://codesandbox.io/s/react-resizable-panels-zf7hwd?file=/src/root.css

Here is a video of the issue using the above codesandbox:

https://user-images.githubusercontent.com/211047/228918481-48c9c4f6-be8b-42a1-bdc7-43a7a695d5dd.mov

**Comment by bvaughn** [comment]
I think you just forgot to pass `collapsible={true}` props to these panels.

https://codesandbox.io/s/react-resizable-panels-zf7hwd?file=/src/App.js

**Comment by incompl** [comment]
> I think you just forgot to pass `collapsible={true}` props to these panels.

I'm sorry @bvaughn I pasted the wrong codesandbox link into the issue. Here is the correct link:

https://codesandbox.io/s/react-resizable-panels-forked-8c8qpo
