### ISSUE TITLE
[Recreated with correct codepen link] Panels do not consistently collapse when they are up against the edge of the viewport

### ISSUE THREAD

**Issue by incompl** [bvaughn/react-resizable-panels#117]
Here is a codesandbox that reproduces the issue: https://codesandbox.io/s/react-resizable-panels-forked-8c8qpo

Here is a video of the issue using the above codesandbox:

https://user-images.githubusercontent.com/211047/228918481-48c9c4f6-be8b-42a1-bdc7-43a7a695d5dd.mov

**Comment by bvaughn** [comment]
Looks like it's a matter of mousing too quickly– such that the last "mousemove" event that fires is _not_ lower than the panel's collapse threshold, and then the mouse has already exited the window (or in this case the iframe) so no more move events are fired.

**Comment by incompl** [comment]
I see, makes sense! Is it possible to disable the drag-to-collapse behavior to avoid this issue, and instead relying entirely on programmatic expand/collapse using buttons?

**Comment by bvaughn** [comment]
Yes, you **could** do that.

I think this is probably also a bug that this library _should_ handle better though. Perhaps we should also listen for an event where the mouse leaves the viewport too

**Comment by bvaughn** [comment]
Fixed in 1638ede.

**Comment by bvaughn** [comment]
0.0.38
