### ISSUE TITLE
Support: Unable to render with direction: vertical

### ISSUE THREAD

**Issue by plam-ml** [bvaughn/react-resizable-panels#121]
I am trying to write some basic code to render the layout in `StoryBook`. With `direction: horizontal` it is working fine, but when I use `direct: vertical` I am unable to see any content unless I set a height that wraps the entirety of `PanelGroup`. Could you provide some guidance/explanation on why this is the case?

Here is the the CodeSandbox link: https://codesandbox.io/s/react-typescript-forked-7g8n7t?file=/src/App.tsx:1750-1758

```
import "./styles.css";

import { ReactNode, useState } from "react";
import { Panel, PanelGroup, PanelResizeHandle } from "react-resizable-panels";

export type SplitPaneProps = {
  panels: ReactNode[];
  direction: "horizontal" | "vertical";
  autoSaveId?: string;
  defaultSizes?: number[];
};

function ResizeHandle() {
  const [isDragging, setIsDragging] = useState(false);

  return (
    <PanelResizeHandle
      style={{
        flex: "0 0 1%"
      }}
      onDragging={setIsDragging}
    >
      <div data-is-dragging={isDragging} />
    </PanelResizeHandle>
  );
}

export function SplitPanes({
  panels,
  autoSaveId,
  direction,
  defaultSizes = []
}: SplitPaneProps) {
  return (
    <PanelGroup autoSaveId={autoSaveId} direction={direction}>
      {panels.map((panel, index) => (
        <>
          <Panel
            key={index}
            order={index}
            defaultSize={defaultSizes[index]}
            className="flex flex-col"
          >
            {panel}
          </Panel>
          {index < panels.length - 1 && <ResizeHandle />}
        </>
      ))}
    </PanelGroup>
  );
}

const panels = [
  <div
    key={1}
    style={{
      whiteSpace: "nowrap",
      height: "300px",
      width: "100%",
      backgroundColor: "red"
    }}
  >
    {"long text here ".repeat(5)}
  </div>,
  <div
    key={2}
    style={{
      whiteSpace: "nowrap",
      height: "300px",
      width: "100%",
      backgroundColor: "yellow"
    }}
  >
    Middle
  </div>,
  <div
    key={3}
    style={{
      whiteSpace: "nowrap",
      height: "300px",
      width: "100%",
      backgroundColor: "blue"
    }}
  >
    Right
  </div>
];

export default function App() {
  return (
    <>
      <SplitPanes panels={panels} direction="vertical" />
    </>
  );
}
```

Thank you!

**Comment by bvaughn** [comment]
The panel group component grows to fill the available width/height. By default, HTML + body + div elements have height: 0.

Set an explicit height (% based or pixel) and it will work.

**Comment by plam-ml** [comment]
@bvaughn Thx, setting flex: 1 1 auto works here. Appreciated

**Comment by plam-ml** [comment]
@bvaughn Thanks a lot for the response. I am looking at here https://codesandbox.io/s/react-resizable-panels-zf7hwd?file=/src/styles.module.css and I am unable to see where it is being set on the style sheet with explicit height. Setting height to 100% on the wrapper in my example does not seem to work, need to be an exact value for me.

**Comment by bvaughn** [comment]
100% only works if the containers are also 100% (HTML, BODY, DIV).

In my example sandbox you linked to, the `root.css` file has:
```css
html,
body {
  width: 100vw;
  height: 100vh;
```
