### ISSUE TITLE
How to allow only predefined values for the size of panels?

### ISSUE THREAD

**Issue by joulev** [bvaughn/react-resizable-panels#122]
If I want a div to only have the sizes of, say, `[25, 50, 75]`, and it would "snap" between those sizes on resizing, how can I do that?

**Comment by bvaughn** [comment]
That's not supported by this library.

**Comment by joulev** [comment]
I see, thanks.

**Comment by bvaughn** [comment]
For what it’s worth, I think it would be possible to add support for that behavior, and I’d be willing to review a PR and consider it. Not sure it’s a feature I would build personally though.
