### ISSUE TITLE
onResize not called from conditional panel changes?

### ISSUE THREAD

**Issue by kayhhh** [bvaughn/react-resizable-panels#123]
`onResize` does not seem to be called for sibling panels when you add a panel to the group (like in the [conditional panels example](https://react-resizable-panels.vercel.app/examples/conditional)), even though it causes the panel to change it's size.

I only just found this project so maybe this is intentional.

**Comment by bvaughn** [comment]
Not sure that this is intentionally, so much as a corner case I hadn't considered.

I imagine there's probably enough info here for me to reproduce the issue.

**Comment by bvaughn** [comment]
This fix will ship in 0.0.51 this morning.
