### ISSUE TITLE
Conditional Panel defaultSize based on window size

### ISSUE THREAD

**Issue by anniebombanie** [bvaughn/react-resizable-panels#125]
Hi, 

I was wondering if the `defaultSize` of a Panel takes conditional values?

I tried using a ternary: `<Panel defaultSize={ isLgScreen ? 20 : 30 } minSize={15} maxSize={33} order={1}>` but this didn't work so I saved it in a variable instead: 

```
const isLgScreen = windowWidth > 1279;
const sidebarDefaultSize = isLgScreen ? 20 : 30;

return (
     ...
     <Panel defaultSize={sidebarDefaultSize}> *panel stuff* </Panel>
)
```

Tried the variable in the same ternary as well as a switch statement to support multiple window widths. However, this doesn't seem to work either. The panel seems to only take into account the last number in all cases. (So in the ternary, it's the `30` and in the switch, it's `default: 20`)

Consoling the `windowWidth` state (window.innerWidth) and the `sidebarDefaultSize` variables returns the expected values so I'm wondering if I'm missing something. I'm working in NextJS if it makes a difference.

Thanks for your help!

**Comment by bvaughn** [comment]
I'm not sure what's going on here exactly since there's no actual code for me to look at.

The `defaultSize` param is only used once– the first time the Panel renders, to set the _initial_ size. After that, any changes to that property **will not affect anything**. Is that perhaps what's confusing you?

**Comment by anniebombanie** [comment]
Omg you're right! I'm sorry - I was working on this at like 4pm on a Friday arvo and my brain was obviously on weekend mode already 🤦‍♀️ Thanks for your answer and please consider this closed.

**Comment by bvaughn** [comment]
No worries :)
