### ISSUE TITLE
Set div css flex-basis， PanelResizeHandle Slow

### ISSUE THREAD

**Issue by Link-Kou** [bvaughn/react-resizable-panels#128]
Whether it can be supported or not can be accelerated by adjusting the number of steps.

![2023-04-25_16-22-56 (1)](https://user-images.githubusercontent.com/22113151/234218711-87f54516-0109-4094-aad4-1dde7f7341a1.gif)

**Comment by bvaughn** [comment]
I don't know what you're reporting here. If it's a bug or a performance issue, you'll need to share a repro (like Code Sandbox or something) not just a picture.

**Comment by Link-Kou** [comment]
Please have a look

https://codesandbox.io/embed/red-http-3gotpk?fontsize=14&hidenavigation=1&theme=dark

@bvaughn

**Comment by bvaughn** [comment]
Sorry. It's still not clear to me _why_ you want to do this. Flex basis and grow are meant to be managed by this library. Overriding those styles will cause problems.

**Comment by Link-Kou** [comment]
@bvaughn 
Normally, the page is proportional.
In fact, the layout needs to be based on the actual size.
For example: left and right layout. I want the largest 300px and the smallest 200px on the left. There is no restriction on the right.

**Comment by bvaughn** [comment]
So this essentially boils down to your wanting support for min/max sizes _in pixels_? That's something I've consciously chosen not to support with this library. (See #114, #46, #47, #78)

I'm going to copy-paste my response form one of those other issues showing how you could tackle your own pixel constraints (if you want to do that) but I don't think you should use `flex-basis` for that.

---

[Here](https://github.com/bvaughn/react-resizable-panels/issues/46#issuecomment-1368108416) is a way you could basically implement this in your application code:

> https://codesandbox.io/s/react-resizable-panels-forked-m5qf69?file=/src/App.js

```js
  const MIN_SIZE_IN_PIXELS = 100;

  const [minSize, setMinSize] = useState(10);

  useLayoutEffect(() => {
    const panelGroup = document.querySelector('[data-panel-group-id="group"]');
    const resizeHandles = document.querySelectorAll(
      "[data-panel-resize-handle-id]"
    );
    const observer = new ResizeObserver(() => {
      let height = panelGroup.offsetHeight;

      resizeHandles.forEach((resizeHandle) => {
        height -= resizeHandle.offsetHeight;
      });

      // Minimum size in pixels is a percentage of the PanelGroup's height,
      // less the (fixed) height of the resize handles.
      setMinSize((MIN_SIZE_IN_PIXELS / height) * 100);
    });
    observer.observe(panelGroup);
    resizeHandles.forEach((resizeHandle) => {
      observer.observe(resizeHandle);
    });

    return () => {
      observer.disconnect();
    };
  }, []);
```

---

[Here](https://github.com/bvaughn/react-resizable-panels/issues/47#issuecomment-1368111142) my reasoning for not wanting to add it to the NPM package directly:

> I think the problem with _this_ is similar to the problem with external width/height props– either can change without `PanelGroup`/`Panel` re-rendering or being aware. (Example: an external stylesheet _could_ define this style.)
> 
> So handling it fully would go from being something triggered only by pointer events to something that could be triggered by a lot of external things.
> 
> I don't think I want to try to support that level of complexity 😄

**Comment by bvaughn** [comment]
Check out https://github.com/bvaughn/react-resizable-panels/pull/176
