### ISSUE TITLE
Expose `getCursorStyle` to be configured 

### ISSUE THREAD

**Issue by plam-ml** [bvaughn/react-resizable-panels#130]
Hello,

I have noticed that the cursor stylings are being set explicitly via this file https://github.com/bvaughn/react-resizable-panels/blob/b78448e14da8264654d2981412a91ff9e14f8835/packages/react-resizable-panels/src/utils/cursor.ts

Would it be possible for us to expose this. I have a use case that requires `ew-resize` and `ns-resize`, and trying to set them via `!important` tag seems to be very buggy (cursor would revert during drag interaction for example).

Thanks

**Comment by bvaughn** [comment]
I don't love the idea of exposing a prop for that, but I would be willing to change "col-resize" to "ew-resize" (and "row-resize" to "ns-resize"). Honestly I'm not sure why you'd specifically use one over the other– and a quick Google search turns up nothing.

"ew-resize" better matches "e-resize" and "w-resize" (which this library also uses) so it seems like an okay change.

**Comment by plam-ml** [comment]
Thanks. Personally I do not have a preference but we want to add a button on the gutter for quick collapse/un-collapse and the styling of `col-resize` and `row-resize` on hover makes it seems a bit inconsistent when adding the chevrons icon on the gutter button.

https://user-images.githubusercontent.com/127577476/234646681-7f69f4f1-15f2-459b-9e25-9ac315c26089.gif

**Comment by bvaughn** [comment]
react-resizable-panels@0.0.42 should work for you
