### ISSUE TITLE
Library is still reaching to window.localstorage even after custom implementation is provided for Storage API

### ISSUE THREAD

**Issue by roshaans** [bvaughn/react-resizable-panels#132]
I have provided a custom implemetnation for the storage API by passing it as a prop to <PanelGroup/>, but even so, the component is reaching out to window.localstorage which causes errors. 

```      
<PanelGroup storage={sessionStorage} direction="vertical">
          <Panel defaultSize={25}>
          </Panel>
          <PanelResizeHandle />
          <Panel>
          </Panel>
</PanelGroup>
```

```
caught DOMException: Failed to read the 'localStorage' property from 'Window': The document is sandboxed and lacks the 'allow-same-origin' flag.
    at eval (webpack-internal:///./node_modules/react-resizable-panels/dist/react-resizable-panels.module.js:639:14)
```

It would be nice to have an option to disable persistance all together.

**Comment by bvaughn** [comment]
The _only_ place `localStorage` is referenced in this project is here:

https://github.com/bvaughn/react-resizable-panels/blob/4242b04ba628622e9f215a8e58615c325e69b84d/packages/react-resizable-panels/src/PanelGroup.ts#L56-L65

The `localStorage` API is **not** used if a custom `storage` prop is provided, and this `typeof` check should never be executed either.

I'm afraid this is going to require a repro case.

**Comment by roshaans** [comment]
Thank you. In order to test this out, you'll need to open this[ CodePen ](https://codepen.io/Roshaan581/pen/poxdavb)URL that has a sandboxed Iframe and then run this repo or any repo that has react-resizable-panels component locally. You can run this example locally: https://github.com/roshaans/react-panels

**Comment by roshaans** [comment]
> Thank you. In order to test this out, you'll need to open this[ CodePen ](https://codepen.io/Roshaan581/pen/poxdavb)URL that has a sandboxed Iframe and then run this repo or any repo that has react-resizable-panels component locally. You can run this example locally: https://github.com/roshaans/react-panels

You should see this in the console window of the CodePen:
![image](https://user-images.githubusercontent.com/25015977/236048951-5cda45f8-d98c-4233-a61e-eddbdef29c58.png)

**Comment by bvaughn** [comment]
> You can run this example locally: https://github.com/roshaans/react-panels

The repository you linked me to runs without any errors for me.

It also does not pass a `storage` prop, so the default storage API (`localStorage`) is used.
