### ISSUE TITLE
Toggling possibility on user interaction

### ISSUE THREAD

**Issue by igortas** [bvaughn/react-resizable-panels#133]
Hi,

I need panes to be toggled on/off, on some user interaction, let's say button click.  As workaround I've manage to achieve this by inline style overriding `flex` style, which also gives me warning message that I need to divide the shorthand `flex` command, line by line. 

If i'm not overriding the `flex` style, collapsing of the panes, works only if user starts moving the resize handles.

Current version of the code snippet:

```
<Fragment>
            {isToggled ? (
              <Panel1
                style={{
                  flex: '95 1 0',
                }}
              >
                {child}
              </Panel1>
            ) : (
              <Panel2
                defaultSize={30}
                minSize={30}
                maxSize={5}
                }}
              >
                {child}
              </Panel2>
            )}
            {index < children.length - 1 && <ResizeHandle /> )}
</Fragment>
```

**Comment by bvaughn** [comment]
Please check out the docs:
https://react-resizable-panels.vercel.app/examples/imperative-panel-api
