### ISSUE TITLE
feat: support RTL

### ISSUE THREAD

**Issue by psychedelicious** [bvaughn/react-resizable-panels#135]
When `document.dir === 'rtl'`, panels resize away from the drag direction:
https://codesandbox.io/p/sandbox/friendly-snyder-nio15q

I'm happy to PR a fix but won't have time until next weekend.

**Comment by bvaughn** [comment]
Happy to look at a PR.

**Comment by bvaughn** [comment]
b23a64d adds support and will release in a few moments with 0.0.44

**Comment by bvaughn** [comment]
0.0.45 released

**Comment by DimaTrollFace** [comment]
POV: It should be a prop and not a **document.dir**

**Comment by psychedelicious** [comment]
Thanks @bvaughn !
