### ISSUE TITLE
Bug: `setLayout` does not update `localStorage` for nested panel groups

### ISSUE THREAD

**Issue by caweidmann** [bvaughn/react-resizable-panels#138]
I have encountered an issue where I try to read from localStorage, but the values which get set do not represent what is on the screen.

Following steps to reproduce:
- View provided link below
- Open DevTools, inspect local storage
- Resize both vertical and horizontal panel groups
- Click the "Reset layout" button
- Notice the UI changes back to default, but only the "primary" local storage item is updated correctly, the "secondary" item still has outdated values

Example: https://codesandbox.io/s/react-resizable-panels-forked-2hlhq8?file=/src/App.js

**Comment by bvaughn** [comment]
Works for me.

**Comment by bvaughn** [comment]
It works for me: https://www.loom.com/share/2ec19ffaffd64ddab333efca36f3599a

**Comment by caweidmann** [comment]
This is what I get when inspecting localStorage:
![2023-05-08 19 43 44](https://user-images.githubusercontent.com/1684894/236894059-aa807440-8eec-48f8-b37c-1d0439168041.gif)

**Comment by bvaughn** [comment]
I think you might need to dig into this, if it's affecting your app. This is just a pet project of mine. No sponsors.

**Comment by caweidmann** [comment]
I'll try and take a look and see if I can figure out what's potting.

**Comment by caweidmann** [comment]
The [debounce](https://github.com/bvaughn/react-resizable-panels/blob/658827be0e4e35e8c52022440785aadd32c33ec1/packages/react-resizable-panels/src/PanelGroup.ts#L50) on saving to localStorage is the issue here. If you have multiple panel groups and you use setLayout to reset them all, e.g.:
```
ref1.setLayout([a,b,c])
ref2.setLayout([d,e,f])
ref3.setLayout([g,h,i])
```
Then only the first write to localStorage will occur and the others will get discarded. Will look into it some more tomorrow.

**Comment by bvaughn** [comment]
Ah! That's a good find.
