### ISSUE TITLE
Panels break when changing minSize

### ISSUE THREAD

**Issue by bartlangelaan** [bvaughn/react-resizable-panels#142]
Hey! Thanks for this amazing package :-)

I tried to implement the trick that allows you to set a minSize based on pixels (from your comment https://github.com/bvaughn/react-resizable-panels/issues/48#issuecomment-1368106118).

However, if I change the minSize, something strange happens. The resize handler starts to work the exact opposite way.

I have made a CodeSandbox example to demonstrate what I mean:
https://codesandbox.io/s/react-resizable-panels-issues-142-vgekmz

Everything works nicely, until the _Break!_ button is clicked. I don't understand how or why.. looks like a bug?

**Comment by bvaughn** [comment]
Give the panels an explicit `order` prop. (I should probably just make this _required_)

**Comment by bartlangelaan** [comment]
Hmm, the documentation states that the `order` prop is only needed if the panels are conditional (which they aren't) or if they have an `onResize` callback (which they don't)..

Is the `order` prop like a key?

**Comment by bvaughn** [comment]
There are other props that- when changed, require a Panel to retegister itself with the PanelGroup- which can cause issues with how the resize handle works (it is associated based on registration order- not visual location on the screen, since there’s no way to know that)

To be clear, this library (at least the docs) cloud do better here- but for now you can fix the issue you’re reporting by adding an “order” prop

**Comment by bvaughn** [comment]
I think I've made a change that will reduce the likelihood of cases like this. (Basically passing a ref rather than the actual panel– so a panel only needs to register/unregister when it mounts/unmounts.)

**Comment by bvaughn** [comment]
0.0.44 should be better in this regard

**Comment by bartlangelaan** [comment]
Confirmed that the issue doesn't appear with 0.0.44! Thanks!!

**Comment by bvaughn** [comment]
Thanks for confirming! I'm glad to hear it.

**Comment by Davenporten** [comment]
Just as additional information: I was having trouble with `minSize` not working with `pixels` (I'd set it to a particular value and it would always be much smaller). When I set `order` the problem was fixed.

Thanks for the great lib!
