### ISSUE TITLE
styled-components doesn't work

### ISSUE THREAD

**Issue by Kikobeats** [bvaughn/react-resizable-panels#143]
Not sure why, but I tried to combine with `styled-compoents` and it seems to don't work.

Minimal reproduction creating a Next.js 13 page:

```jsx
'use client'

import styled from 'styled-components'

import {
  PanelGroup as PanelGroupBase,
  Panel as PanelBase,
  PanelResizeHandle
} from 'react-resizable-panels'

const PanelGroup = styled(PanelGroupBase)`
  height: 100vh;
`

const Panel = styled(PanelBase)`
  background: '#192230';
`

export default function Page () {
  return (
    <PanelGroup direction='vertical'>
      <Panel maxSize={75}>top</Panel>
      <PanelResizeHandle />
      <Panel maxSize={75}>bottom</Panel>
    </PanelGroup>
  )
}
```

**Comment by bvaughn** [comment]
I've never used "styled-components" but so far as I know, it's just syntactic sugar for converting inline styles into a `className` prop.

I pasted your code above into [Code Sandbox](https://codesandbox.io/s/affectionate-shadow-m5cj3f?file=/src/App.js) and it looks like it _sort of works_. Here's the `PanelGroup` element:
<img width="203" alt="Screen Shot 2023-05-12 at 7 08 03 PM" src="https://github.com/bvaughn/react-resizable-panels/assets/29597/297fb061-ba74-480e-96c0-5d97dc5c1c85">

So the custom style is applied, though it's lower priority than the default.

The `Panel` element is another matter:
<img width="198" alt="Screen Shot 2023-05-12 at 7 08 59 PM" src="https://github.com/bvaughn/react-resizable-panels/assets/29597/871c96f7-508e-4d80-94e8-291a0aa2ab7f">

I don't know why "styled-components" would turn the style value into that invalid string, but I don't use or support that library so I can't really help you with that.

I also added a regular function component and tried styling it with styled-components and it did the same thing:
```js
function Example({ children, className }) {
  return <div className={className}>{children}</div>;
}

const StyledExample = styled(Example)`
  background: "#192230";
`;
```

From what I can see, this doesn't look like an issue with _this library_ so much as a general question about styled-components and function components.

Sorry, I can't help with that!

**Comment by Kikobeats** [comment]
You actually helped, thanks!

You're right: styled-components is applying styles via classnames, while `react-resizable-panels` is adding some default styles using `style` prop, so `!important` should be used for overwriting them 🙂

Here the example working:

```jsx
import styled from 'styled-components'

import {
  PanelGroup as PanelGroupBase,
  Panel as PanelBase,
  PanelResizeHandle
} from 'react-resizable-panels'

const PanelGroup = styled(PanelGroupBase)`
  height: 100vh !important;
  color: white;
`

const Panel = styled(PanelBase)`
  background: #192230;
  color: white;
`

export default function Page () {
  return (
    <PanelGroup data-debug direction='vertical'>
      <Panel maxSize={75}>top</Panel>
      <PanelResizeHandle />
      <Panel maxSize={75}>bottom</Panel>
    </PanelGroup>
  )
}
```
