### ISSUE TITLE
Collapsible panel behaviour

### ISSUE THREAD

**Issue by jacobator** [bvaughn/react-resizable-panels#149]
When resizing a collapsible panel it is being collapsed when it reaches 0 width and uncollapsed when it reaches `minSize` width.

VSCode's (and other's) side panel collapse is triggered at a `minSize / 2` width, which is a much better user experience.

Any chance you could update collapse/uncollapse to trigger at a `minSize / 2` by default or allow to customize the trigger at size?

**Comment by bvaughn** [comment]
Added in 0.0.47
