### ISSUE TITLE
Panels methods onResize and onCollapse are not triggered when setLayout is called

### ISSUE THREAD

**Issue by Sloebel** [bvaughn/react-resizable-panels#154]
Hi,

On screen that I develop, I'm using the collapse feature, once I'm forcing a layout on the `PanelGroup` with the `setLayout` method,  `onResize` or `onCollapse` methods on `Panel` are not triggered 

4 Panels example: 
while being in sizes state of `[10, 20, 70, 0]`, I'm calling `setLayout([10, 0, 45, 45])`
the second Panel is not ware that he is in collapse state and the 4th Panel isn't aware that he is out from collapse state

any suggestions?

Thanx in advance

**Comment by bvaughn** [comment]
Seems related to #123.

Not a high priority for me but I'd be willing to review a PR.

**Comment by bvaughn** [comment]
I'll release this fix with 0.0.51 this morning.
