### ISSUE TITLE
Expand panel to size it was before collapsing

### ISSUE THREAD

**Issue by rijk** [bvaughn/react-resizable-panels#163]
First off: great package, works smoothly and was fun to implement. 👌

Only hickup I had was the following. For a UI like this:

https://github.com/bvaughn/react-resizable-panels/assets/159500/6f9c478f-099b-4dca-afaa-acb66951dc18

which I think is pretty common use of collapse/expand functionality, I had to do some extra work to keep track of the last value the panel had before it was collapsed (because collapsing sets the width to `0`).

It's not hard, it's basically this:

```tsx
const preferred = useRef<number | null>(panel) // panel is the value passed from the cookie

// Setting the ref:

<PanelGroup
  direction="horizontal"
  onLayout={(sizes) => {
    const panel = sizes.at(-1)
    document.cookie = `panels:timeline=${panel}`
    if (panel && panel > 0) preferred.current = panel
  }}

// Button:

<button
  className="button text-sm py-1.5 text-sky-600 bg-sky-100 hover:bg-sky-200"
  onClick={() =>
    ref.current?.getCollapsed()
      ? ref.current?.resize(preferred.current || DEFAULT_SIDEBAR_PERCENT)
      : ref.current?.collapse()
  }
>
  Feedback
</button>

```

But it would be nice if the package did this automatically when calling `ref.current?.expand()`. If you think this would fit in your vision for the scope of course.

Thanks!

**Comment by bvaughn** [comment]
What you describe should be the default behavior. There are even end to end tests to verify it:
https://github.com/bvaughn/react-resizable-panels/blob/936a5b8e7902a7cf48fa5cf28d9f0fa6fb951d15/packages/react-resizable-panels-website/tests/ImperativePanelApi.spec.ts#L106-L189

I'm guessing something else is going on in your project if this is not working. Without a Code Sandbox repro though, I can't help.

**Comment by rijk** [comment]
Oh shoot! I'll set up a repro this weekend. Thanks 🙏

**Comment by rijk** [comment]
Okay, it actually does 🙈

The reason it was not working for me was I was already using `.resize` instead of `.expand` because I didn't like how the first time you expand it (given it started off collapsed), it expands to the panel's `minSize`. Is there a smart way around that? Something like `defaultSize` but only when expanded.

1. Initial: [100, 0] (first panel `defaultSize={100} minSize={50}`, second panel `defaultSize={0} minSize={20}`)
2. Expand panel: [80, 20] <- would like it to be [65, 35]
3. Resize panel
4. Collapse
5. Expand to previous size

**Comment by bvaughn** [comment]
Got it.

I think what you’re describing there _makes sense_, but I don’t think I want to add it as the library’s default behavior.

I think you should be able to implement it though:
1. Use state to track if the panel has collapsed/expanded before
2. If no, use resize(defaultSize)
3. If yes, use expand()

**Comment by rijk** [comment]
Aight, makes sense. Thanks!

**Comment by bvaughn** [comment]
Thanks for understanding! 🤝  Good luck!

**Comment by rijk** [comment]
Hey just an idea: what do you think about adding an optional parameter to `expand()`?

```ts
expand(defaultSize?: number)
```

**Comment by bvaughn** [comment]
Just use resize(). What you’re describing is the same, no?

**Comment by rijk** [comment]
Uhm I don't think so, the idea is the `defaultSize` would only be used if there is no internal `sizeBeforeCollapse`.

So [this](https://github.com/bvaughn/react-resizable-panels/blob/936a5b8e7902a7cf48fa5cf28d9f0fa6fb951d15/packages/react-resizable-panels/src/PanelGroup.ts#L590-L591) would change to something like (if we call this param `preferredSize` to avoid confusion):

```ts
    const sizeBeforeCollapse =
      panelSizeBeforeCollapse.current.get(id) || preferredSize || minSize;
```

**Comment by bvaughn** [comment]
I dunno. Initial reaction is no but I’ll think about it
