### ISSUE TITLE
[Question] React resizable panels vs react flexlayout

### ISSUE THREAD

**Issue by ThimoDEV** [bvaughn/react-resizable-panels#164]
Hello,

Since the early versions of this package I was impressed by its potential!
Currently I use https://github.com/caplin/FlexLayout in my project to render multiple layouts as tabs (like the Unity Editor/Unreal Editor etc)

I was wondering if the features that react flexlayout has that resizeable panels is missing are interesting to add to this package/on the roadmap?

![image](https://github.com/bvaughn/react-resizable-panels/assets/68739517/7e057b7b-7731-45a2-9ab1-bcec8a30ed3e)

**Comment by bvaughn** [comment]
This is a pretty broad question.

Some of the things in the list you pasted above are already supported by this library. Others (like "tabs" and "theming") aren't related to resizing and so they wouldn't be something that would belong in a project like this.

If that library has been working well for you, I wouldn't recommend switching to this one 😄  If there are things about hat one that don't work well, then you could probably build a lot of the things you've described above _on top of_ a library like this (as its own project).

Hope this answer was helpful!
