### ISSUE TITLE
Flex reverse

### ISSUE THREAD

**Issue by stecb** [bvaughn/react-resizable-panels#173]
Hey @bvaughn, first of all thanks a lot for the lib, it's excellent! You deserve way more than just a coffee!

So, we implemented a "resizable" layout, and it works perfectly, but we're trying to achieve something probably unsupported by the lib. As inside of the panels there're some components w/ some (complex) state/interactions, and we also want to be able to "swap" them (i.e. left w/ the right one), we naively thought about "hacking" it via setting `flex-direction: row-reverse` to the `GroupContainer`. It actually _works_, but of course the resize handlers do not work as expected, as they go in the opposite direction (see attached screen rec). 

https://github.com/bvaughn/react-resizable-panels/assets/122819/1e217865-5bf0-413c-8933-0262fd83f169

Given we can't actually easily take a snapshot of the state inside of the panels and re-hydrate them if we actually "swap" them via a re-render, i.e. 

```jsx
const leftContent = isMainContentLeft ? MainContent : SideContent
const rightContent = isMainContentLeft ? SideContent : MainContent

return (
  <PanelGroup direction="horizontal">
    <Panel>{leftContent}</Panel>
    <PanelResizeHandle />
    <Panel>{rightContent}</Panel>
  </PanelGroup>
);
```

Do you see any other possible "hacks" to make it work by "visually" swapping the panels? 🤔 Or maybe there's something hidden in the props we can use.

Thanks again.

**Comment by bvaughn** [comment]
Can you give me a narrowed down repro to look at? (Like a link to that Code Sandbox the video was made from?)

> You deserve way more than just a coffee!

Well okay if you insist

**Comment by stecb** [comment]
> Can you give me a narrowed down repro to look at? (Like a link to that Code Sandbox the video was made from?)
> 

Well that video was just from your codesandbox's demo, I just added a style obj to it + made it horizontal.

If you want I can make another one.

> 
> 
> > You deserve way more than just a coffee!
> 
> 
> 
> Well okay if you insist

Bear w me!

Thanks again! 🙏

**Comment by bvaughn** [comment]
I see. Yes, I think it would be useful for you to give me an example that is close to what you want as possible, and then I can try an idea or two. Otherwise I might be solving the wrong problem.

**Comment by stecb** [comment]
Here you go https://codesandbox.io/s/react-resizable-panels-forked-jjl225?file=/src/App.js

**Comment by bvaughn** [comment]
Thanks. This is very helpful.

I was on-call this week so I didn't have a lot of extra time but I'll try to take a look this afternoon.

**Comment by bvaughn** [comment]
Here you go: https://codesandbox.io/s/react-resizable-panels-forked-7zzz83

Based on what you've described, I think this should work for you:
* Render panel content as portals, so you can move it around without losing component state.
* Use `onLayout` and `panel.resize()` to swap sizes when you swap panels.

**Comment by bvaughn** [comment]
Here you go: https://codesandbox.io/s/react-resizable-panels-forked-7zzz83

Based on what you've described, I think this should work for you:
* Render panel content as portals, so you can move it around without losing component state.
* Use `onLayout` and `panel.resize()` to swap sizes when you swap panels.

---

❤️ → ☕ [givebrian.coffee](http://givebrian.coffee/)

**Comment by stecb** [comment]
> Here you go: https://codesandbox.io/s/react-resizable-panels-forked-7zzz83
> 
> 
> 
> Based on what you've described, I think this should work for you:
> 
> * Render panel content as portals, so you can move it around without losing component state.
> 
> * Use `onLayout` and `panel.resize()` to swap sizes when you swap panels.
> 
> 
> 
> ---
> 
> 
> 
> ❤️ → ☕ [givebrian.coffee](http://givebrian.coffee/)

N1! Thanks 🙏

**Comment by stecb** [comment]
Hey @bvaughn sorry to bother again, I think I still have the same issue, as the actual content ("holding" the state) is coming as a prop, and I actually need to "inject" it into the Panels, see [example here](https://codesandbox.io/s/react-resizable-panels-forked-8p69kf?file=/src/App.js)

Do you have any ideas? 🤔

**Comment by bvaughn** [comment]
Don't really understand what you're saying, sorry.

**Comment by bvaughn** [comment]
State is state. It shouldn't matter if it's in the immediate component or a nested one. I suspect something else is going wrong.

**Comment by bvaughn** [comment]
I suspect what's happening is that this–
```js
if (container == null) {
  return null;
}
```
–is rendering in between when you swap, which is unmounting and remounting your nested component.

**Comment by bvaughn** [comment]
Hmm. Maybe there's a quirk about portal behavior that I was not familiar with :( Possibly related to https://github.com/facebook/react/issues/12247?

If a portal _doesn't_ work for this, another fallback solution would be to lift this state outside of the component (by passing it in as a prop or using something like context)

I don't think this is really within the realm of resizable panels at this point. (Even if it were, unfortunately I don't really have the bandwidth to dig into it anymore at the moment.)

**Comment by stecb** [comment]
Ah thanks, and I totally agree about the latter sentence. Even tho I think I could give it a try w/ the (horizontal/vertical)-reverse behaviour and see if I can get it working just via reversing the flex. 

Thanks 🙏🏼

**Comment by stecb** [comment]
FYI, I've made it working flawlessly w/ https://github.com/httptoolkit/react-reverse-portal

👇🏼 

```jsx
// ...

const swappedPortalLeft = swappedPanels ? (
  <portals.OutPortal node={portalNodeLeft} />
) : (
  <portals.OutPortal node={portalNodeRight} />
);
const swappedPortalRight = swappedPanels ? (
  <portals.OutPortal node={portalNodeRight} />
) : (
  <portals.OutPortal node={portalNodeLeft} />
);

return (
  <>
    <PanelGroup direction="horizontal" onLayout={setLayout}>
      <Panel
        ref={panelLeftRef}
        style={{
          ...((!showSplitPanel || isDigitalResults) && !contentNavRight && { flexGrow: 0 }),
        }}
      >
        {swappedPortalLeft}
      </Panel>
      {!isDigitalResults && (
        <PanelResizer
          key={swappedPanels ? "swapped" : "normal"}
          showSplitPanel={showSplitPanel}
          setIsDragging={setIsDragging}
          isDragging={isDragging}
        />
      )}
      <Panel
        ref={panelRightRef}
        style={{
          ...((!showSplitPanel || isDigitalResults) && contentNavRight && { flexGrow: 0 }),
        }}
      >
        {swappedPortalRight}
      </Panel>
    </PanelGroup>
    <portals.InPortal node={portalNodeLeft}>{mainContent}</portals.InPortal>
    <portals.InPortal node={portalNodeRight}>{extraContent}</portals.InPortal>
  </>
);
  ```

**Comment by bvaughn** [comment]
Glad you got it sorted out! Thanks for sharing the solution
