### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'getBoundingClientRect')

### ISSUE THREAD

**Issue by mjsilva** [bvaughn/react-resizable-panels#175]
Hi and thank you for this great library!

All of the sudden I started getting this weird error on my nextjs app.

My code is simple 

```typescript
"use client";

import { Panel, PanelGroup, PanelResizeHandle } from "react-resizable-panels";

export default function Home() {
  return (
    <>
      <div className="grid h-screen text-neutral-200 grid-cols-main">
        <div className="border-r border-neutral-700 bg-black"></div>
        <div className="border-r border-neutral-700 bg-neutral-800"></div>
        <PanelGroup direction="horizontal">
          <Panel className="bg-neutral-800" defaultSize={20}>
            Testing
          </Panel>
          <PanelResizeHandle className="bg-neutral-700 w-0.5" />
          <Panel className="bg-neutral-800" defaultSize={50}></Panel>
        </PanelGroup>
      </div>
    </>
  );
}
```
Here's the full console log dump: [localhost-1690283379442.log](https://github.com/bvaughn/react-resizable-panels/files/12160405/localhost-1690283379442.log)

I've tried to restart, delete next.js caches, delete node modules... Nothing seems to work. I'm a bit lost what else todo. Any thing else anyone can think I should try to fix it?

**Comment by bvaughn** [comment]
There isn't enough info here for me to look into this. Can you share a way for me to run the code? Preferably a smaller repro of the bug you're seeing.

**Comment by mjsilva** [comment]
Hey @bvaughn thanks for getting back! 

Here's the repo with a replicable issue: https://github.com/mjsilva/react-resizable-panel-nextjs-issue

Instructions
1. Clone it
2. npm install
3. npm run dev
4. access http://localhost:3000

This should get you the error.

Some more info on my system:
```
❯ node --version
v18.16.0

❯ npm --version
9.6.7

❯ system_profiler SPSoftwareDataType SPHardwareDataType
Software:

    System Software Overview:

      System Version: macOS 13.3.1 (22E261)
      Kernel Version: Darwin 22.4.0

Hardware:

    Hardware Overview:

      Model Name: MacBook Pro
      Model Identifier: MacBookPro18,1
      Model Number: Z14V000YCX/A
      Chip: Apple M1 Pro
      Total Number of Cores: 10 (8 performance and 2 efficiency)
      Memory: 32 GB
      System Firmware Version: 8422.121.1
      OS Loader Version: 8422.100.650
```

**Comment by mjsilva** [comment]
Just done some more tests and it looks like it broke on nextjs [v13.4.11](https://github.com/vercel/next.js/releases/tag/v13.4.11). It woks fine on [v13.4.10](https://github.com/vercel/next.js/releases/tag/v13.4.10)

**Comment by bvaughn** [comment]
That seems pretty useful, that you've narrowed down the commit range like that.

Using your repo above (thanks!) I recorded a Replay of the error here:
https://app.replay.io/recording/1a7ecc46-af7a-4e64-b23b-202b4a23f61c

Looking at the Replay (I added some comments) I _think_ this might be a bug with Next.js + React's `useId`. I think this bug report should probably be moved to Next.js (with a pointer to the Replay above).

**Comment by mjsilva** [comment]
thank you so much @bvaughn. I confirm that passing and explicit id fixes the issue. Should I report this to https://github.com/vercel/next.js repo?

**Comment by bvaughn** [comment]
Yes, I think the `useId` issue should probably be reported to next. I don't think there's anything I can do on this side.

**Comment by bvaughn** [comment]
I'm going to close this issue since I don't think there's anything I can do on this side. Please do let me know what Next says about the issue you open though.
