### ISSUE TITLE
Unable to resize panels in Electron

### ISSUE THREAD

**Issue by Derp33** [bvaughn/react-resizable-panels#177]
The following works fine in `v0.0.53` but in  `v0.0.54` panels are locked to the `defaultSize` and cannot be resized.
```tsx
import { Panel, PanelGroup } from 'react-resizable-panels';
import ResizeHandle from './components/ResizeHandle';

function App() {
  return (
    <>
      <PanelGroup direction="horizontal">
        <Panel defaultSize={50} minSize={10} collapsible={true}>Test Panel 1</Panel>
        <ResizeHandle/>
        <Panel defaultSize={50} minSize={10} collapsible={true}>Test Panel 2</Panel>
      </PanelGroup>
    </>
  );
}

```

**Comment by bvaughn** [comment]
Bug reports need a full repro. You didn't share the `ResizeHandle` component, so I can't rule out that it's correctly wrapping the `PanelResizeHandle` component from this library.

Here are Code Sandbox links I put together:
* [repro w/ 0.0.53](https://codesandbox.io/s/affectionate-ben-hn8k8p)
* [repro .w/ 0.0.54[(https://codesandbox.io/s/frosty-goldstine-n55mc7)

Both versiopns seem to work fine for me.

**Comment by bvaughn** [comment]
By the way, the difference between 0.0.53 and 0.0.54 bundles is _very_ minimal– mostly comments, and one switch to use a package export condition for the is-browser check:
```diff
2a3,4
> const isBrowser = typeof window !== "undefined";
> 
24,25c26
< const canUseEffectHooks = !!(typeof window !== "undefined" && typeof window.document !== "undefined" && typeof window.document.createElement !== "undefined");
< const useIsomorphicLayoutEffect = canUseEffectHooks ? useLayoutEffect : () => {};
---
> const useIsomorphicLayoutEffect = isBrowser ? useLayoutEffect : () => {};
39,42d39
< 
< // Workaround for Parcel scope hoisting (which renames objects/functions).
< // Casting to :any is required to avoid corrupting the generated TypeScript types.
< // See github.com/parcel-bundler/parcel/issues/8724
109a107
>     idWasAutoGenerated: idFromProps == null,
120a119
>     panelDataRef.current.idWasAutoGenerated = idFromProps == null;
160,163d158
< 
< // Workaround for Parcel scope hoisting (which renames objects/functions).
< // Casting to :any is required to avoid corrupting the generated TypeScript types.
< // See github.com/parcel-bundler/parcel/issues/8724
823a819,823
>   useRef({
>     didLogDefaultSizeWarning: false,
>     didLogIdAndOrderWarning: false,
>     prevPanelIds: []
>   });
1271,1274d1270
< 
< // Workaround for Parcel scope hoisting (which renames objects/functions).
< // Casting to :any is required to avoid corrupting the generated TypeScript types.
< // See github.com/parcel-bundler/parcel/issues/8724
1410,1413d1405
< 
< // Workaround for Parcel scope hoisting (which renames objects/functions).
< // Casting to :any is required to avoid corrupting the generated TypeScript types.
< // See github.com/parcel-bundler/parcel/issues/8724
```

My guess is, if anything is causing weirdness for you with Electron, it must be the is-browser conditional– which maybe points to your project's build setup?

**Comment by Derp33** [comment]
Hmm. I can't work out why the check would fail. My first thought was maybe somehow this check was being performed in preload causing window to be undefined. But both checking if window is present and wrapping the components in `React.lazy` yielded the same results. 

The `ResizeHandle` just applies a bg colour similar to your example.

When I get a mo, I'll try to reproduce in a clean repo and reopen if necessary.
Thanks for pointing out the potential problems.

**Comment by aleksbobic** [comment]
Hey @bvaughn I had a similar issue with a fresh electron-forge project (with electron version 27.0.1 using the vite typescript template). It seems some of the default styles aren't applied and the PanelResizeHandle has no width defined (also there's no icon). I'd have to dig deeper to figure out what's the proper fix but just adding a custom style where the width and a background color is defined makes the element visible and also the entire PanelGroup resizable. 

Example code: 

```jsx
    <PanelGroup direction="horizontal">
      <Panel defaultSize={20}>Panel 1</Panel>
      <PanelResizeHandle style={{ width: "10px", backgroundColor: "blue" }} />
      <Panel defaultSize={50}>
        <Text>Well hello</Text>
        <Button>Click</Button>
      </Panel>
      <PanelResizeHandle />
      <Panel defaultSize={30}>Panel 3</Panel>
    </PanelGroup>```

**Comment by bvaughn** [comment]
Thanks for that added context!
