### ISSUE TITLE
Panel onCollapse no longer triggering in 0.0.55

### ISSUE THREAD

**Issue by mjchang** [bvaughn/react-resizable-panels#183]
First off, thanks for the work on getting pixel units working 🙏 I've have a use-case where I have a fixed pixel size panel so I was trying out the latest version. However, I noticed that the `onCollapse` is not triggered anymore.

**Demo**
https://codesandbox.io/s/react-resizable-panels-forked-39pctn?file=/src/App.js

**Comment by bvaughn** [comment]
Thanks for the repro. Hopefully I can address this as part of the exploration I'm looking into as part of #182, but it will likely be several days because I'm on call at my day job this week.

**Comment by psychedelicious** [comment]
I was confused because `onCollapse` is working for me on v55. Reviewing your demo I noticed two things:
- the repro has a typo in the `onCollapse` prop
- if I omit the `collapsedSize` prop, the cb is fired

**Comment by mjchang** [comment]
Ooops good find - I updated the repro. `onCollapse` is triggered on initial mount but not afterwards

**Comment by bvaughn** [comment]
#182 has been merged and I should be publishing v56 this afternoon. I think this issue will be addressed by it so I'm going to close it for now.
