### ISSUE TITLE
Layout Issues

### ISSUE THREAD

**Issue by dawi** [bvaughn/react-resizable-panels#185]
Hello @bvaughn, thank you for implementing this library.

I have a few issues while integrating this library into an existing project and would like to give some feedback. :)
I have seen that you are currently rewriting some internals, so maybe all my points are already known, but maybe it will help, I don't know. :)

I have an application with a pretty basic layout.

* A left sidebar, the content and a right sidebar. 
* The user has the possibility to resize, expand or collapse the sidebars. 
* The sidebar state (collapse state and width in pixel) is stored in local storage.

---

After I found this library and I wanted to replace our own sidebar logic with this much more elegant library.

Thereby I have the following issues:

1. Since our current layout uses state variables to decide weather the sidebars should be visible, I chose the approach to conditionally render the sidebars. However, if I conditionally toggle the left sidebar, the size of the right sidebar changes as well (although I am using pixel units). This behavior may be caused by this: `If an autoSaveId is provided, layouts will be stored separately for each panel combination.`

2. Because of this, I tried the imperative approach. At first it looked good: If the user toggles a sidebar, it does not effect the width of the opposite sidebar. The issue have is the following: If a sidebar is collapsed, the user reloads the page and afterwards expands the sidebar again, it does not expand to its previous width.

3. Third I tried to grab the size of the panel in onResize() and provide it as defaultSize to the Panel. There, although I am using pixel units, I get percentage values, so I switched the layout to percentage. This solution finally worked for me, however it feels more like a workaround for me.

A last note: In our application I am now using the imperative API to collapse the sidebars. Therefore the sidebars have to be collapsible. But I don't want the auto-collapse behavior. It would be nice if it could be configured seperately.

Thanks again for this great library. :)

**Comment by bvaughn** [comment]
Hey @dawi. I'm not sure what I can do with this issue. Without a repro, there's nothing I can really look at.

If you want to use pixel based constraints, I suggest waiting for v56 (#182) since that should hopefully simplify things a lot.

**Comment by dawi** [comment]
Hey @bvaughn, I think I will wait for v56 then as you suggested. :)

**Comment by bvaughn** [comment]
Thanks!
