### ISSUE TITLE
Allow resizing orphan panels

### ISSUE THREAD

**Issue by viveleroi** [bvaughn/react-resizable-panels#186]
In #93 I described our desire to resize an "orphan panel". Think of a "drawer" at the side of an application that slides in and out, positioned absolutely, that doesn't have a sibling panel. 

Now that you've been working on a system to support pixel sizes, it's occurred to me that you're closer to enabling this and am opening this issue to see what you think. 

I'm thinking you'd need a new prop/setting to opt-in to this feature so it's not the default.

Sadly there's no way `flex` can't be used on absolutely positioned children. [Source](https://www.w3.org/TR/css-flexbox-1/#abspos-items) so this would require height/width. 

The positioning logic for the `PanelResizeHandle` will probably be more complicated given it's outside of the absolute element, but this seems doable given your recent dive into pixel stuff.

I can imagine this drawer/one panel need might be fairly common, our use case is a little complicated as we allow the user to toggle between `position: absolute` and not, but I still feel this is worth considering.

**Comment by bvaughn** [comment]
This use case still sounds uncommon enough that I don't think it's something I want to build support for.

**Comment by bvaughn** [comment]
Thanks for understanding 🙇🏼
