### ISSUE TITLE
Multiple calls to `collapse()` and `expand()` require delay

### ISSUE THREAD

**Issue by psychedelicious** [bvaughn/react-resizable-panels#187]
## Problem
The imperative API methods `collapse()` and `expand()` do not work as expected when called in quick succession. Only the last call works as expected. Maybe the other imperative methods have the same issue but I haven't tested them.

## Repro
https://codesandbox.io/s/react-resizable-panels-forked-7p2yyl?file=/src/App.js

edit: realized that cs is on v39 - here's v55, where the issue is the same:
https://codesandbox.io/p/sandbox/react-resizable-panels-forked-4xyrnn?file=%2F.codesandbox%2Ftasks.json%3A1%2C1

Observations
- the plain `toggle` only toggles the last panel
- the `setTimeout` version works but you have to give enough delay between each call
- the `requestAnimationFrame` version works for the first & last calls, but calls between them do not work

I wonder if this is related to react batching updates interacting with interaction with DOM via refs?

## Usecase
I have multiple panels and want to use the imperative API to collapse multiple panels at the same time. I'd like to be able to iterate over a number of panel refs and collapse them all.

## Alternative
Can use the `PanelGroup` imperative API to do this, but it's a bit awkward to do the math and idenify the right indices manually. 

Another useful change might be to extend the `PanelGroup` imperative API with methods like
- `getCollapsedByIds(ids: string[])`
- `expandIds(ids: string[])`
- `collapseIds(ids: string[])`
- `resizeIds({id: string, size: number}[])`

**Comment by bvaughn** [comment]
I think what you've hit on is that Panel sizes are stored inside of React, and React state updates are not synchronous by default (because generally this results in better batching behavior for multiple, unrelated updates). If you do need a synchronous update, then `flushSync` seems like a good route. :)

> I'm happy for this to be closed as resolved, unless you'd like to address this internally.

I appreciate it!
