### ISSUE TITLE
Collapsed panels expand on screen orientation change (e.g. tablet)

### ISSUE THREAD

**Issue by psychedelicious** [bvaughn/react-resizable-panels#188]
Collapsed panels expand on screen orientation change (e.g. tablet):
https://github.com/bvaughn/react-resizable-panels/assets/4822129/0609fe05-a01b-43be-84a6-296bc3109b38

Fortunately also happens in FF responsive preview mode:
https://github.com/bvaughn/react-resizable-panels/assets/4822129/8320a8eb-24f0-4eec-a135-2a7320e60784

**Comment by bvaughn** [comment]
#182 has been merged and I plan to release v56 this afternoon with the changes. I'm closing old issues in light of the rewrite because most of them are no longer relevant. If this issue still occurs with v56, please re-open with an updated description on how to reproduce it.
