### ISSUE TITLE
ResizeObserver loop completed with undelivered notifications

### ISSUE THREAD

**Issue by igortas** [bvaughn/react-resizable-panels#189]
Hi,

I'm starting getting this issue for quite some time, even the library is updated frequently, currently happens also on the latest version.
In my scenario this error happens, when I frequently navigate between tabs which opens component per tab click (lazy loaded or not).

Part of wrapper code that I'm reusing on multiple places and providing some init config, nothing different from the basic example):

```
<PanelGroup
      direction='horizontal'
      disablePointerEventsDuringResize
    >
      {panes.map((child, index) => {
        return (
              <Panel
              >
                {child}
              <Panel>
                />
              )}
        );
      })}
    </PanelGroup>
```

Error:

```
ResizeObserver loop completed with undelivered notifications.
    at handleError (http://localhost:3000/static/js/bundle.js:269489:58)
    at http://localhost:3000/static/js/bundle.js:269508:7
```

Happens on microsoft edge, I'll check if happens the same on mozilla or not...

**Comment by bvaughn** [comment]
> I'm starting getting this issue for quite some time, even the library is updated frequently, currently happens also on the latest version.

That sounds odd, because `ResizeObserver` wasn't used in this project until ~2 weeks ago (#176) in the latest release.

I'm sorry to hear that you're hitting this. This isn't enough of a repro for me to investigate or fix though.

I do plan on removing `ResizeObserver` from panels that don't use pixel percentages in the next release (pending #182) which may help your case.

**Comment by igortas** [comment]
@bvaughn Found similar topics for this error on stackoverflow, and I've tried the weirdest fix, removing LastPass extension. So far looks good.

**Comment by bvaughn** [comment]
That's interesting.

**Comment by bvaughn** [comment]
#182 has been merged and I plan to release v56 this afternoon with the changes. I'm closing old issues in light of the rewrite because most of them are no longer relevant.

FWIW for this specific issue, `ResizeObserver` will only be referenced if pixel based constraints are used.
