### ISSUE TITLE
How to display layer content that is clipped by overflow: hidden?

### ISSUE THREAD

**Issue by yangshun** [bvaughn/react-resizable-panels#191]
## Issue

I'm running into an issue where I'm using Monaco editor within panels and the default `overflow: hidden` styling on `Panel` and `PanelGroup` is clipping the contents. I don't have control over the stacking context and DOM rendering position of the popovers as they're rendered by Monaco editor.

<img width="1508" alt="image" src="https://github.com/bvaughn/react-resizable-panels/assets/1315101/64a94536-7ca8-4dca-88f9-d73e8a872836">

## Repro

1. Go to https://react-tile-manager.vercel.app/playground/react-ts.
2. Hover over the right `</h1>` and see that the popover is being clipped.

## My Initial Attempt

My initial attempt was to specify `style={{overflow: 'visible'}}` for every `Panel` and `PanelGroup` to override the default `overflow: hidden` property. However, this messes up with the layout and the resizing doesn't work well.

Seems like `overflow: hidden` is necessary but I don't have control over how the popover is rendered I don't know of a good way to solve this.

**Comment by bvaughn** [comment]
Nah, I don’t think a custom prop is needed for this. I would suggest doing just what you’re doing (or use a CSS class and !important rule)

🙂

**Comment by saalihou** [comment]
@bvaughn I am not sure how this is a workaround, when you set `overflow: visible` on the panels, resizing becomes choppy and does not end up where you place it. This seems like a bug

https://github.com/bvaughn/react-resizable-panels/assets/9271500/0feb4c2b-3363-4c2d-9378-e1e48b056277

**Comment by rinorzk** [comment]
having the exact same issue

**Comment by omermesser** [comment]
I encountered the same issue and drew inspiration from @wardxela's idea, successfully implementing data attributes. Here's what I added:

For the `PanelGroup` component:
```
      <PanelGroup
        direction="horizontal"
        className="!overflow-visible"
      >
```

And to the `Panel` component:
```
<Panel
          defaultSize={40}
          className={`!overflow-visible data-[panel-size="0.0"]:!overflow-hidden`
          )}
          minSize={10}
          collapsible
        >
```
Just a small note: I noticed some issues with smaller sizes, which is why I used the collapsible feature to address this.
