### ISSUE TITLE
Vertically resizing a panel that is hidden and then shown again results in resize direction being flipped

### ISSUE THREAD

**Issue by sebpowell** [bvaughn/react-resizable-panels#192]
Hi there, thank you for this library! 

I've been having a play with this today, and came across an issue whereby a panel that is toggled off / on after the user clicks 'Toggle middle-top panel', when resized, resizes in the opposition direction; moving the mouse up results in it getting larger, and moving it down, smaller. 

Repro sandbox here: https://codesandbox.io/s/react-resizable-panels-forked-5vk4sj?file=/src/App.js

And video of what's happening:

https://github.com/bvaughn/react-resizable-panels/assets/1786366/3d01ed9d-10a5-477b-b142-caaaecc1d042

Any ideas what the issue might be? Thank you in advance!

**Comment by bvaughn** [comment]
Yup, you're just missing an `order` prop. In the common case, this library can infer the order based on when panels mount and register with a parent group– but if panels are dynamically hidden and shown, then it needs to be specified explicitly.

https://codesandbox.io/s/react-resizable-panels-forked-r887xg

The [docs](https://react-resizable-panels.vercel.app/examples/conditional) do mention this, but it's probably too subtle:
> Panels can be conditionally rendered. **The `order` ensures they are (re)added in the correct order.**
