### ISSUE TITLE
Resize cursor style is not always cleared after resizing is finished

### ISSUE THREAD

**Issue by armano2** [bvaughn/react-resizable-panels#193]
Styles for global cursor sometimes are not reset when collapsing panels

source: https://github.com/typescript-eslint/typescript-eslint/pull/7672
https://deploy-preview-7672--typescript-eslint.netlify.app/play

https://github.com/bvaughn/react-resizable-panels/assets/625469/3afcf48f-d695-4f82-a6d2-e0c1e771e7dd

**Comment by bvaughn** [comment]
#182 has been merged and I plan to release v56 this afternoon with the changes. I'm closing old issues in light of the rewrite because most of them are no longer relevant. If this issue still occurs with v56, please re-open with an updated description on how to reproduce it.
