### ISSUE TITLE
Fixed size panel during container resize

### ISSUE THREAD

**Issue by timdown** [bvaughn/react-resizable-panels#195]
Thank you for this library. It very nearly does everything we need. One thing missing is the ability to have a panel whose absolute size does not change when its container is resized. VS Code's side bar is a good example of this, as illustrated in #114. The requirement is:

- The panel should stay the same size when its container is resized. Other panels in the group should adjust to fill the remaining space
- The panel should otherwise be resizable via a resizer in the usual way

I've tried to do this using a `ResizeObserver`, `getSize` and `resize`; it pretty much works but the resizer wobbles a bit as you resize, and it feels dirty given that the library also has a `ResizeObserver` doing a similar job. I'd make an example on CodeSandbox but its latest version of the library is 0.0.37. This is the kind of thing I tried:

```typescript
function FixedPanelExample() {
  const fixedPanelRef = useRef<ImperativePanelHandle>(null)
  const fixedPanelPixelWidthRef = useRef(0)

  function updateFixedPanelWidthRef() {
    fixedPanelPixelWidthRef.current =
      fixedPanelRef.current?.getSize('pixels') || 0
  }

  useLayoutEffect(() => {
    updateFixedPanelWidthRef()

    const groupElement = document.querySelector(
      `[data-panel-group-id="fixedPanelGroup"]`
    )
    if (!groupElement) return

    const resizeObserver = new ResizeObserver(() => {
      fixedPanelRef.current?.resize(fixedPanelPixelWidthRef.current, 'pixels')
    })

    resizeObserver.observe(groupElement)

    return () => resizeObserver.unobserve(groupElement)
  }, [])

  return (
    <PanelGroup id="fixedPanelGroup" direction="horizontal">
      <Panel
        id="fixedPanel"
        ref={fixedPanelRef}
        defaultSize={20}
        collapsible
        onResize={updateFixedPanelWidthRef}
      >
        Fixed under container resize
      </Panel>
      <PanelResizeHandle style={{ backgroundColor: 'black', width: '10px' }} />
      <Panel collapsible>Fluid</Panel>
    </PanelGroup>
  )
}
```

Could a better implementation be added to the library or is there a better way to do this now?

**Comment by bvaughn** [comment]
This doesn't sound like a use case I want to support. It sounds pretty niche (and I think supporting it in the library would be pretty complicated). Good luck though!

**Comment by timdown** [comment]
Fair enough. I am surprised it's niche, because it's precisely what VS Code does, but the lack of other requests for this suggests you're right.

**Comment by bvaughn** [comment]
That's true! First time I've heard of it though. :)

**Comment by city17** [comment]
I'm looking for the exact same functionality, would be great if this were possible.

**Comment by pkelaita** [comment]
I'm surprised this is niche as well! I've been looking for a way to do this for a collapsable sidebar. Any chance plans to support this have changed?

**Comment by bvaughn** [comment]
Nope. Not a use case I’ve ever had.

**Comment by arkangel-dev** [comment]
I agree its a use case that would def be helpful. For example Im working on an electron app and Im using this for side panel. Right now it grows and shrinks with the window. @bvaughn Would you consider it if I made a PR?

**Comment by bvaughn** [comment]
I’m in the middle of a very large rewrite of this library, #528, so now is not a good time to open a PR. (Thank you for the offer though!)

Side note: Surprising to notice 👎🏼 reactions to respectful replies in this thread. Writing a library like this, and docs, and answering questions here is a lot of unpaid work. It should be totally okay for me to politely refuse a requested feature if I feel like I don’t have the time or energy to support it.

**Comment by bvaughn** [comment]
Version 4.6.0 adds support for disabling panel resize: https://react-resizable-panels.vercel.app/examples/disabled-panels

**Comment by arkangel-dev** [comment]
I think you mean to link to this @bvaughn https://react-resizable-panels.vercel.app/examples/fixed-size-panels

**Comment by bvaughn** [comment]
Either option works, but if you're looking for _panels_ with fixed sizes, that can now be done by just _disabling_ the panel. (If you want to render a non-panel with a fixed size, then that's supported too! and would be the link you shared) 😄
