### ISSUE TITLE
Allow `PanelGroup` to receive additional props

### ISSUE THREAD

**Issue by AmirTugi** [bvaughn/react-resizable-panels#196]
Heya, I noticed that `PanelGroup` renders a component and passes some styling and data props.
[Here](https://github.com/bvaughn/react-resizable-panels/blob/main/packages/react-resizable-panels/src/PanelGroup.ts#L903)'s where this magic happens.

Something I'd like to ask is the ability to pass any additional props along.
In my case I am wrapping with another div as a workaround, but it would be nice to be able to avoid a div soup and pass the relevant props directly to `PanelGroup`.

Cheers! 🥂

**Comment by bvaughn** [comment]
Feel free to open a PR with a proposal and I will look it over.

**Comment by bvaughn** [comment]
I will support this in v1.0 (#230)
