### ISSUE TITLE
MarqueeSelection

### ISSUE THREAD

**Issue by giuliohome** [bvaughn/react-resizable-panels#198]
[Same question](https://github.com/yyllff/split-pane-react/issues/22) here:

I've found that MarqueeSelection is causing an issue and the split panels do not resize.

As a workaround I've had to delete the MarqueeSelection component: do you know what is going on?

Anyway I'm happy with this workaround and I've moved to this solution because it works also in case of mobile devices.

**Comment by bvaughn** [comment]
No. I’m not familiar with that component, sorry.

**Comment by giuliohome** [comment]
I believe that the answer of ChatGPT - written here
https://github.com/yyllff/split-pane-react/issues/22#issuecomment-1751597615 - is correct: that's the reasonable explanation I was looking for.
