### ISSUE TITLE
How can we get panel height?

### ISSUE THREAD

**Issue by kasvith** [bvaughn/react-resizable-panels#200]
Hi, love this library and your efforts

I was using this for creating a layout, it requires the panel height to do an internal height calculation.
I've been using `units="pixels"` but it doesn't give me the pixel value of the panel height on `onResize` event.

is there any workaround for this?

**Comment by bvaughn** [comment]
#182 has been merged and I plan to release v56 this afternoon with the changes. All sizes are now reported in both percentage and pixel units.
