### ISSUE TITLE
Forcing handle cursor style while dragging

### ISSUE THREAD

**Issue by MohammadElokour** [bvaughn/react-resizable-panels#203]
During dragging the handle a global css cursor style is added that cant be overwitten:
![image](https://github.com/bvaughn/react-resizable-panels/assets/48622340/48e78c4d-9a59-4178-a664-7965908d28dc)

Even when overwriting it with !important I can see the default cursor style outside the boundaries of resizer itself during dragging state because of the nature of the applied CSS style (which is using the star notation that applies the style pretty much everywhere)

can this be removed? so we can have the flexibly to choose our own cursor style

**Comment by bvaughn** [comment]
Feel free to open a PR with a proposal and I will look it over.

**Comment by bvaughn** [comment]
Thank you for reporting this. I've decided not to make any changes here though, primarily because I'm not sure *how* I would support this.

**Comment by bvaughn** [comment]
I know this is an old issue, but react-resizable-panels@3.0.4 now supports cursor customization. Docs and example at https://react-resizable-panels.vercel.app/examples/custom-cursor
