### ISSUE TITLE
`PanelOnResize` arg `prevMixedSizes` typed as required but is not present on init

### ISSUE THREAD

**Issue by psychedelicious** [bvaughn/react-resizable-panels#208]
v57
Repro: https://codesandbox.io/p/sandbox/stoic-elion-fp8m2n

Note the console output for `prevMixedSizes` is `undefined` on init

I think it makes sense to leave the type as required and make `prevMixedSizes === mixedSizes` on init. That's a nicer than typing it as optional and needing to do a lot of checks.

**Comment by bvaughn** [comment]
The type is incorrect for the initial render. My apologies.

**Comment by bvaughn** [comment]
react-resizable-panels@0.0.58 has been published with this fix
