### ISSUE TITLE
Cannot expand/collapse panel immediately on mount

### ISSUE THREAD

**Issue by bvaughn** [bvaughn/react-resizable-panels#211]
Context: https://github.com/bvaughn/react-resizable-panels/issues/206#issuecomment-1809369778

Repro: https://codesandbox.io/s/gracious-cannon-h5stq4

**Comment by timdown** [comment]
`resize()` also throws an error (probably unsurprisingly).

**Comment by bvaughn** [comment]
The timing of this is interesting. The API calls are being made before the panel has registered itself with the parent group.

**Comment by bvaughn** [comment]
The overall problem is this:

- On mount, panels register with their parent group.
- The group schedules state updates with the newly registers panels (to re-render them with their appropriate sizes, based on their props/constraints).
- Your code is calling collapse (or expand, or resize) in between these two events– when the panel group isn't yet tracking the panels. (They're still in a pending-update state.)

Maybe I could change the `registerPanel` handler to update the `committedValuesRef` synchronously (to store the new panels) but I suspect other things might break if that's the only change. I'll look into this further soon though.

**Comment by bvaughn** [comment]
Fix published in @0.0.59

**Comment by bvaughn** [comment]
I don't love my fix. Filed #217 to follow up with a better approach.

**Comment by bvaughn** [comment]
0.0.60 fixes this in a better way.
