### ISSUE TITLE
Enter key keyboard interaction doesn't work according to Window Splitter Spec

### ISSUE THREAD

**Issue by dawa-coursera** [bvaughn/react-resizable-panels#213]
Hi, we're trying to use this library but the Enter key keyboard doesn't seem to work as specified by the [Window Splitter spec](https://www.w3.org/WAI/ARIA/apg/patterns/windowsplitter/). Any plans to support this?

> Enter: If the primary pane is not collapsed, collapses the pane. If the pane is collapsed, restores the splitter to its previous position.

**Comment by bvaughn** [comment]
I have an e2e test verifying the "Enter" behavior here:
https://github.com/bvaughn/react-resizable-panels/blob/main/packages/react-resizable-panels-website/tests/WindowSplitter.spec.ts

I was improperly collapsing between min size, not collapsed size. I'll fix that.

That being said, I don't think I will aim to support this part (for now):
> If the pane is collapsed, restores the splitter to its previous position.

I think for now that collapsed panels will just restore to their minimum size.

**Comment by bvaughn** [comment]
Addressed with 4c01bf2; will publish shortly.

**Comment by bvaughn** [comment]
Fix published in @0.0.59

**Comment by dawa-coursera** [comment]
Thanks @bvaughn! Will test the fix.

**Comment by dawa-coursera** [comment]
Hi @bvaughn, is the issue here just bandwidth and prioritization, or is this something that would not be feasible with the library?  

> That being said, I don't think I will aim to support this part (for now)
  > If the pane is collapsed, restores the splitter to its previous position.

**Comment by bvaughn** [comment]
Mostly the former.
