### ISSUE TITLE
`getCollapsed` removed in latest version 0.0.57?

### ISSUE THREAD

**Issue by AmruthPillai** [bvaughn/react-resizable-panels#214]
```
apps/client/src/stores/builder.ts:100:38 - error TS2551:  
Property 'getCollapsed' does not exist on type 'WritableDraft<ImperativePanelHandle>'.  
Did you mean 'collapse'?
          98 | 
          99 |         if (panelRef) {
       > 100 |           const collapsed = panelRef.getCollapsed();
             |                                      ^
         101 |           collapsed ? panelRef.expand() : panelRef.collapse();
         102 |         } else {
         103 |           state.sheet[side].open = !state.sheet[side].open;
```

I was depending on the `getCollapsed` getter function to toggle whether or not the panel should be triggered. But I see that it has been removed in the later versions. Is there an alternative for this, or should I downgrade for now?

**Comment by AmruthPillai** [comment]
Similarly, I'm getting this error as well.

![Screenshot 2023-11-18 at 8 28 43 AM](https://github.com/bvaughn/react-resizable-panels/assets/1134738/3c322086-aec7-4868-9ec8-9b5d0e4f609f)

**Comment by bvaughn** [comment]
Very sorry. Looks like I missed a docs update. The API is now `isCollapsed()` (or `isExpanded()` if you prefer). I will update the docs this morning.

**Comment by bvaughn** [comment]
react-resizable-panels@0.0.58 has been published with this fix

**Comment by AmruthPillai** [comment]
Thank you for your continued support on the library, it's works great for my use-case!

**Comment by bvaughn** [comment]
Happy to hear it!
