### ISSUE TITLE
Nested layouts default to zero on size

### ISSUE THREAD

**Issue by shaoruu** [bvaughn/react-resizable-panels#218]
As can be seen in the attached video, when rerendering a new nested layout, the sub-layout would have a zero of size at first. Upon clicking on the resize handle, the sub-layout would snap back to the expected size. Any ideas why this is happening?

Thanks!

https://github.com/bvaughn/react-resizable-panels/assets/35216312/7c5430b8-c113-430a-a510-27aa3810470a

**Comment by bvaughn** [comment]
Need a repro. Can't debug a video.

**Comment by bvaughn** [comment]
A code sandbox would work, but a [Replay](https://replay.io/) would be even better.

**Comment by shaoruu** [comment]
Let me quickly get a repo to replicate this issue. Thanks

**Comment by shaoruu** [comment]
I created a new repo and tried replicating this issue. Turns out it's because the video above was using `v0.0.55`. As soon as I upgraded to `v0.0.59`, the issue was gone. 

Thanks for this amazing library!

**Comment by bvaughn** [comment]
Glad to hear! :)
