### ISSUE TITLE
[Next.js 14 SSR] Layout changes after client hydration

### ISSUE THREAD

**Issue by binghuis** [bvaughn/react-resizable-panels#225]
Next.js 14 + react-resizable-panels: 0.0.63

When the page is initialized, there is still a flickering issue. I implemented SSR rendering according to the cookies solution in the readme, but the problem persists. I looked at some previous related issues and found that some methods seemed to be outdated.

https://github.com/bvaughn/react-resizable-panels/assets/20395726/ac3749ad-c3d4-40aa-a9ed-22c9861806e1

**Comment by binghuis** [comment]
<img width="873" alt="image" src="https://github.com/bvaughn/react-resizable-panels/assets/20395726/2b044a85-3955-4123-8c36-e90dbaa14acd">
<img width="706" alt="image" src="https://github.com/bvaughn/react-resizable-panels/assets/20395726/b4b378e6-62f9-406e-92fe-8264c1f818cf">

**Comment by binghuis** [comment]
this is my repo https://github.com/binghuis/chat-whiz/blob/main/app/page.tsx

**Comment by binghuis** [comment]
Is there something wrong with how I'm using it? Please give me some hints.

**Comment by bvaughn** [comment]
Glad you got it sorted out.
