### ISSUE TITLE
Panel doesn't respect minSizePixels when resizing window

### ISSUE THREAD

**Issue by itsjackgardner** [bvaughn/react-resizable-panels#231]
You can force a panel to be smaller then the designated `minSizePixels` by resizing the window, this causes some snap jank when going to resize the panel afterwards.

## Reproduction steps:

1. Use a pixel based layout: https://react-resizable-panels.vercel.app/examples/pixel-based-layouts
2. Give a panel a `minSizePixels`
3. Resize window to force the panel to be smaller than it's min size

https://github.com/bvaughn/react-resizable-panels/assets/30457534/23d4b23b-28e7-4f6a-9d1a-90495753f46e

**Comment by bvaughn** [comment]
Hey @itsjackgardner. I've decided to drop pixel support. There are just too many edge cases, and I don't need that functionality in any of my apps. I've been preparing v1.0 release (#230) but I'm not quite finished with it yet. Hopefully soon.

**Comment by bvaughn** [comment]
I am going to close this issue since it won't be relevant in the v1.0 release. I'm sorry the pixel experiment didn't pan out but I just don't have the time/energy to maintain that much of an API. Thanks for understanding. 🙇🏼
