### ISSUE TITLE
Reversed Drag Direction🔄

### ISSUE THREAD

**Issue by BrodyRas** [bvaughn/react-resizable-panels#232]
## Bug 🪲
While using a nested Panel layout, the vertical Resize Handle is resizing in the wrong direction 😅

## Evidence 📑
![reverse](https://github.com/bvaughn/react-resizable-panels/assets/49171024/0c65fa3d-3a71-46b7-b0d7-239bf07fc736)

## Structure 🏛️
```html
<PanelGroup direction="horizontal">
  <Panel id='left-drawer' defaultSize={15} minSize={15} order={1}>
    <LeftDrawer/>
  </Panel>   
  <ResizeHandle />
  <Panel>
    <PanelGroup direction="vertical">
      <Panel id='main' minSize={30} order={2} >
        <Main/>
      </Panel>
      <ResizeHandle />
      <Panel defaultSize={10} minSize={10} order={3}>
        <Bottom/>
      </Panel>
    </PanelGroup>
  </Panel>
</PanelGroup>
```

**Comment by bvaughn** [comment]
That's interesting. This works on the docs site: https://react-resizable-panels.vercel.app/examples/nested

I've copied your code above to Code Sandbox so it's runnable though and it does seem to repro there:
https://codesandbox.io/p/sandbox/react-resizable-panels-issues-232-z7zgjt

**Comment by bvaughn** [comment]
Here's a Replay of the bug:
[app.replay.io/recording/5d66f740-f021-4486-9d5f-1eb580f6d9e2](https://app.replay.io/recording/5d66f740-f021-4486-9d5f-1eb580f6d9e2)

**Comment by bvaughn** [comment]
Ah! It's the `order` prop. You haven't specified it on the 2nd panel, so it's getting sorted before the first panel.

**Comment by BrodyRas** [comment]
Thanks so much! That fixed it 👍
