### ISSUE TITLE
Assertion failed error

### ISSUE THREAD

**Issue by rortan134** [bvaughn/react-resizable-panels#233]
Version 1.0.1

![image](https://github.com/bvaughn/react-resizable-panels/assets/37253958/483dc298-f1b8-4bae-9cd2-ee235b40d213)
![image](https://github.com/bvaughn/react-resizable-panels/assets/37253958/29a280ed-b624-432d-b8e9-04589944ace2)

```tsx
<PanelGroup direction="horizontal" onLayout={onLayout}>
      <Panel order={1}>{/* ... */}</Panel>
      <PanelResizeHandle />
      <Panel order={2}>{/* ... */}</Panel>
      <PanelResizeHandle />
      <Panel order={3}>{/* ... */}</Panel>
    </PanelGroup>
```

**Comment by bvaughn** [comment]
@rortan134 I'm going to need more of a repro than this. Can you share a Code Sandbox that reproduces the bug you're seeing? I have no idea what's in your `app-index.js` file on line 32.

**Comment by rortan134** [comment]
app-index is dev (nextjs) compiled code
![image](https://github.com/bvaughn/react-resizable-panels/assets/37253958/f498287f-1d6f-4a93-ae22-17a921992fb1)

Reverting back to 0.64 works fine (with the props changed)

[reproduction](https://codesandbox.io/p/devbox/drawer-snap-points-forked-z6ns97?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clpn68mr200083j6ip4xrmkyf%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clpn68mr100033j6ig4uciu1f%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clpn68mr100053j6iondiss60%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clpn68mr200073j6izza4jfuk%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B52.663181947597806%252C47.336818052402194%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clpn68mr100033j6ig4uciu1f%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpn68mr100023j6ig8ewvbcc%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A35%252C%2522startColumn%2522%253A9%252C%2522endLineNumber%2522%253A35%252C%2522endColumn%2522%253A9%257D%255D%252C%2522filepath%2522%253A%2522%252Fapp%252Fmy-drawer.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clpn68mr100033j6ig4uciu1f%2522%252C%2522activeTabId%2522%253A%2522clpn68mr100023j6ig8ewvbcc%2522%257D%252C%2522clpn68mr200073j6izza4jfuk%2522%253A%257B%2522id%2522%253A%2522clpn68mr200073j6izza4jfuk%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpn68mr200063j6ixdn3lmhg%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clpn68mr200063j6ixdn3lmhg%2522%257D%252C%2522clpn68mr100053j6iondiss60%2522%253A%257B%2522id%2522%253A%2522clpn68mr100053j6iondiss60%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpn68mr100043j6iz3c0loyv%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clpn68mr100043j6iz3c0loyv%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by bvaughn** [comment]
The sandbox you linked to me does not log or throw any errors. Works fine.

**Comment by bvaughn** [comment]
Looking at your code, it is worth pointing out that you have invalid constraints:
```jsx
        <ResizablePanel order={0} minSize={200} maxSize={300}></ResizablePanel>
        <ResizablePanelHandle />
        <ResizablePanel order={1} minSize={200} maxSize={200}></ResizablePanel>
        <ResizablePanelHandle />
        <ResizablePanel order={2} minSize={200} maxSize={300}></ResizablePanel>
```

Min and max sizes should be percentages (0-100%) so 200% and 300% aren't valid numbers.

**Comment by rortan134** [comment]
>  Looking at your code, it is worth pointing out that you have invalid constraints:

I abstracted it so I can pass in pixel values (look at the my-drawer.tsx components)

> 
The sandbox you linked to me does not log or throw any errors. Works fine.

I just tried it in two other browsers and it seems to happen consistently (Opera above and chrome below)
![image](https://github.com/bvaughn/react-resizable-panels/assets/37253958/bf920049-db84-4933-9d3f-fb8c23fa8b6c)

**Comment by bvaughn** [comment]
I'm testing on Chrome and it doesn't happen for me. My guess is that there's a problem in your abstraction somewhere.

**Comment by bvaughn** [comment]
You might be able to [record a Replay](https://www.replay.io/) of the bug happening which would be helpful for me to look at (but Replay is also Gecko based so maybe not)

**Comment by rortan134** [comment]
Oh wow, turns out I still had the panels persisted layout stored in localStorage on every browser I tested from previous updates and mistakenly reused the same panels IDs on every test I did... Sorry for the misunderstanding.

**Comment by bvaughn** [comment]
No problem. That’s an easy mistake to make.

I’m not sure how to detect and warn about this case, but it does seem like some thing that I could maybe do a better job of surfacing in development mode

any ideas?

**Comment by rortan134** [comment]
> No problem. That’s an easy mistake to make.
> 
> I’m not sure how to detect and warn about this case, but it does seem like some thing that I could maybe do a better job of surfacing in development mode
> 
> any ideas?

I guess you could attach a version identifier to the stored localstorage key and compare it with the current package version on first render. The only reason this happened though is that we went from defaultSize to defaultSizePixels back to defaultSize, so I don't think it'll be happening again now that it's at 1.0 right?

**Comment by bvaughn** [comment]
> The only reason this happened though is that we went from defaultSize to defaultSizePixels back to defaultSize, so I don't think it'll be happening again now that it's at 1.0 right?

I think that's true.

**Comment by bvaughn** [comment]
Updated the storage key to avoid this scenario in 1.0.2
