### ISSUE TITLE
Assertion Failed

### ISSUE THREAD

**Issue by Ailakks** [bvaughn/react-resizable-panels#239]
Hello,
I'm getting this error when trying to use this library.

![image](https://github.com/bvaughn/react-resizable-panels/assets/93053643/e0210216-6ff6-4392-a84a-df3d4163d47b)

**Comment by bvaughn** [comment]
Sorry. There is no way I can help. You haven’t provided any kind of repro or information.

**Comment by Ailakks** [comment]
Sorry. This is the full error. Seems to be caused by this line.
![image](https://github.com/bvaughn/react-resizable-panels/assets/93053643/62522857-bd73-4cfd-824f-543720ca6b95)
![image](https://github.com/bvaughn/react-resizable-panels/assets/93053643/54354a5a-f4a2-4d60-a4a2-ac551e9dce0d)

**Comment by bvaughn** [comment]
I don't need the error. I need a repro (code that I can run to reproduce the error).

**Comment by bvaughn** [comment]
Easiest for you would probably be for you to share your app/code with me (so that I can run it and debug how it got into this unexpected state). If you can't do that, maybe you can reproduce the behavior in a Code Sandbox or something. (If you can't do either, I won't be able to help.)

**Comment by Ailakks** [comment]
fixed, sorry, was my fault with conditional rendering

**Comment by bvaughn** [comment]
Gotcha. No prob

**Comment by bvaughn** [comment]
Ilillvqrii
