### ISSUE TITLE
Missing changelogs for 1.0.0+?

### ISSUE THREAD

**Issue by viveleroi** [bvaughn/react-resizable-panels#241]
We're on v0.55 but yarn upgrade is saying that 1.0.4 is the latest. Looking at the releases tab, I don't see any entries for 1.0 and I don't see a CHANGELOG.md file or anything. 1.0 has at least one change and breaks for us so I wanted to be sure I'm not missing where the upgrade notes are posted?

I get warnings about `disablePointerEventsDuringResize` which appears to have been removed or renamed.

**Comment by bvaughn** [comment]
A changelog can be found here:
https://github.com/bvaughn/react-resizable-panels/blob/main/packages/react-resizable-panels/CHANGELOG.md

The `disablePointerEventsDuringResize` prop was unintentionally removed in 0.0.56, as it was kind of an edge case prop and that version was a major rewrite. Sorry for missing it.

**Comment by wkirby** [comment]
@bvaughn if it was unintentionally removed, will it be restored? Or is the expectation that we implement that functionality ourselves.

**Comment by bvaughn** [comment]
I don't think I intentionally removed it, just that it got removed as part of a major refactor when I was still in the pre-1.0 stage. I don't really have a need for it, so I wasn't planning on re-adding it.
