### ISSUE TITLE
`onCollapse` doesn't work.

### ISSUE THREAD

**Issue by hbseo** [bvaughn/react-resizable-panels#244]
react-resizable-panels: 1.0.5

This is my code  in Panel component
`
onCollapse={(collapsed: boolean) => { console.log(collapsed); }}
`

### Problem
1. collapsed value is undefined when the panel is collapsed.
2. ts(2322) type `(collapsed: boolean) => void`  is not assignable to type `PanelOnCollapse`

**Comment by billy-syrett** [comment]
`onCollapse` doesn't send the state. I'm handling it by storing the state outside the component:

```ts
onCollapse={() => setIsCollapsed(true)}
onExpand={() => setIsCollapsed(false)}
```

**Comment by hbseo** [comment]
It works thanks. I referred to [packages/react-resizable-panels/README.md](https://github.com/bvaughn/react-resizable-panels/tree/main/packages/react-resizable-panels) but I don't think it's updated.
I think [react-resizable-panels-website](https://react-resizable-panels.vercel.app/) is updated. I'll refer to this.
