### ISSUE TITLE
onCollapse type issue

### ISSUE THREAD

**Issue by step2341** [bvaughn/react-resizable-panels#245]
im trying to do this:  

const [isCollapsed, setIsCollapsed] = React.useState(defaultCollapsed) 

<ResizablePanel
          defaultSize={defaultLayout[0]}
          collapsedSize={navCollapsedSize}
          collapsible={true}
          minSize={15}
          maxSize={20}
          onCollapse={(collapsed) => {
            setIsCollapsed(collapsed)
            document.cookie = `react-resizable-panels:collapsed=${JSON.stringify(
              collapsed
            )}`
          }}
          className={cn(isCollapsed && "min-w-[50px] transition-all duration-300 ease-in-out")}
        >

i get a type error: Type '(collapsed: any) => void' is not assignable to type 'PanelOnCollapse'.
  Target signature provides too few arguments. Expected 1 or more, but got 0.ts(2322)
Panel.d.ts(62, 5): The expected type comes from property 'onCollapse' which is declared here on type 'IntrinsicAttributes & Omit<HTMLAttributes<ElementType>, "id" | "onResize"> & { className?: string | undefined; ... 11 more ...; tagName?: ElementType | undefined; } & { ...; } & RefAttributes<...>' and im not able to get the collapse to work.  whats the correct method?

**Comment by billy-syrett** [comment]
`onCollapse` doesn't send the state. I'm handling it by storing the state outside the component:

```ts
onCollapse={() => setIsCollapsed(true)}
onExpand={() => setIsCollapsed(false)}
```

**Comment by step2341** [comment]
ok cool thanks i didnt i missed the expand handler. that makes it easy. ended up doing this: const handleCollapse = () => {
    setIsCollapsed(true);
    document.cookie = `react-resizable-panels:collapsed=${JSON.stringify(true)}`;
  };

  const handleExpand = () => {
    setIsCollapsed(false);
    document.cookie = `react-resizable-panels:collapsed=${JSON.stringify(false)}`;
  }; that way can persist the state etc..

**Comment by bvaughn** [comment]
Thanks @billy-syrett!
