### ISSUE TITLE
Dosnt work in NextJs 

### ISSUE THREAD

**Issue by MVARUNREDDY8203** [bvaughn/react-resizable-panels#246]
```
"use client";
import { Panel, PanelGroup, PanelResizeHandle } from "react-resizable-panels";

export default function Home() {
    return (
        <PanelGroup direction='horizontal'>
            <Panel defaultSize={30} minSize={20}>
                <div>Hi</div>
            </Panel>
            <PanelResizeHandle />
            <Panel minSize={30}>middle</Panel>
            <PanelResizeHandle />
            <Panel defaultSize={30} minSize={20}>
                <div>hi right</div>
            </Panel>
        </PanelGroup>
    );
}
//page.js 
```
![image](https://github.com/bvaughn/react-resizable-panels/assets/94187286/8a66493e-8473-4c03-b4c9-8cc9d4aa2eaf)

Here is what im getting as output
![image](https://github.com/bvaughn/react-resizable-panels/assets/94187286/e1770ca1-a4d1-4073-ab5f-075dae1422d0)
Its rendering the divs but no resizable components
pls help

**Comment by nickdc8** [comment]
Add some styling to them. 
`<PanelResizeHandle className="w-2 bg-blue-800" />`

**Comment by MVARUNREDDY8203** [comment]
still doesnt work
![image](https://github.com/bvaughn/react-resizable-panels/assets/94187286/c3a75e16-1550-4e17-89bb-88343224fb6f)
![image](https://github.com/bvaughn/react-resizable-panels/assets/94187286/56f3e6aa-5fa0-44c3-bcfc-a92abacfb53d)

**Comment by bvaughn** [comment]
Give me a link to something I can run in my browser, or a Git repo I can check out and run locally. It is inefficient to try to trouble shoot issues by looking at pictures of code.

**Comment by MVARUNREDDY8203** [comment]
https://github.com/MVARUNREDDY8203/test_resizable_panels heres the url of  github repo of my local project

**Comment by bvaughn** [comment]
@MVARUNREDDY8203 The problem is that you haven't given any meaningful CSS styles to your resize handles, so they're effectively invisible.
![Screenshot 2023-12-29 at 9 51 22 AM](https://github.com/bvaughn/react-resizable-panels/assets/29597/7277eedc-e99c-42ce-a2e5-5bc565ffe282)

Adding Tailwind classes to them (`w-2 bg-blue-800`) doesn't do much if you aren't including Tailwind in your project (which it seems you aren't, because no Tailwind styles are applied anywhere so far as I can see). If I apply manual styles to your components, they "work"

```diff
diff --git a/src/app/page.tsx b/src/app/page.tsx
index 13b7588..66809d0 100644
--- a/src/app/page.tsx
+++ b/src/app/page.tsx
@@ -2,17 +2,23 @@
 import { Panel, PanelGroup, PanelResizeHandle } from "react-resizable-panels";
 
 export default function Home() {
-    return (
-        <PanelGroup direction='horizontal'>
-            <Panel defaultSize={30} minSize={20}>
-                <div>Hi</div>
-            </Panel>
-            <PanelResizeHandle className='w-2 bg-blue-800' />
-            <Panel minSize={30}>middle</Panel>
-            <PanelResizeHandle className='w-2 bg-blue-800' />
-            <Panel defaultSize={30} minSize={20}>
-                <div>hi right</div>
-            </Panel>
-        </PanelGroup>
-    );
+  return (
+    <PanelGroup direction="horizontal" style={{ height: 400 }}>
+      <Panel defaultSize={30} minSize={20}>
+        <div>Hi</div>
+      </Panel>
+      <PanelResizeHandle
+        className="w-2 bg-blue-800"
+        style={{ width: 5, backgroundColor: "red" }}
+      />
+      <Panel minSize={30}>middle</Panel>
+      <PanelResizeHandle
+        className="w-2 bg-blue-800"
+        style={{ width: 5, backgroundColor: "red" }}
+      />
+      <Panel defaultSize={30} minSize={20}>
+        <div>hi right</div>
+      </Panel>
+    </PanelGroup>
+  );
 }
```

This seems like a project configuration issue.

**Comment by bvaughn** [comment]
This looks like a common enough problem that I added a section about it to the FAQ:
https://github.com/bvaughn/react-resizable-panels?tab=readme-ov-file#why-dont-i-see-any-resize-ui

**Comment by MVARUNREDDY8203** [comment]
I would have loved a how to get started section with this specified. I can help create that.

**Comment by MVARUNREDDY8203** [comment]
Its working now, thanks for the quick resolve @bvaughn
