### ISSUE TITLE
No Tooltip animation using manual installation method 

### ISSUE THREAD

**Issue by lacymorrow** [bvaughn/react-resizable-panels#247]
Using ShadCN "Mail" example inside electron-react-boilerplate with manual installation, there are no tooltip animations (they appear/disappear instantly)

**Comment by bvaughn** [comment]
This repo is not ShadCN and has nothing to do with tooltips or animations. Sorry.

**Comment by lacymorrow** [comment]
Whoops, my bad, wrong repo.
