### ISSUE TITLE
Feature Request: Access underlying DOM elements via Imperative API

### ISSUE THREAD

**Issue by psychedelicious** [bvaughn/react-resizable-panels#248]
## Request

With the removal of pixel-based layouts, it'd be nice to have direct access to the underlying DOM elements via the Imperative API.

For example, `panelGroupRef.current.element` could be a ref to the panel group div, and `panelRef.current.element` could be a ref to the panel div.

The specific use-case I'm thinking about is checking the size of the panel elements, to implement some pixel constraints outside the library.

## Alternatives Considered

1. Use `querySelector` to grab them based on data attributes. Awkward, requiring keeping track of however many panel & panel group IDs.
```js
document.querySelector('[data-panel-group-id="app"] [data-panel-id="gallery"]')
```

2. Wrap the panels in other elements and access them via refs. Gets messy, cluttering the DOM with divs.

**Comment by bvaughn** [comment]
I have some utilities that I use internally for querying the underling DOM elements:
https://github.com/bvaughn/react-resizable-panels/tree/main/packages/react-resizable-panels/src/utils/dom

I think it would be reasonable to export these publicly, for people like yourself who want to interop with the underlying DOM. Let me think about it.

**Comment by bvaughn** [comment]
I just published 1.0.6 with those methods exported. You can use them like so:

```js
import {
  getPanelElement,
  getPanelGroupElement,
  getResizeHandleElement,
  Panel,
  PanelGroup,
  PanelResizeHandle,
} from "react-resizable-panels";

export function Example() {
  const refs = useRef();

  useEffect(() => {
    const groupElement = getPanelGroupElement("group");
    const leftPanelElement = getPanelElement("left-panel");
    const rightPanelElement = getPanelElement("right-panel");
    const resizeHandleElement = getResizeHandleElement("resize-handle");

    // If you want to, you can store them in a ref to pass around
    refs.current = {
      groupElement,
      leftPanelElement,
      rightPanelElement,
      resizeHandleElement,
    };
  }, []);

  return (
    <PanelGroup direction="horizontal" id="group">
      <Panel id="left-panel">{/* ... */}</Panel>
      <PanelResizeHandle id="resize-handle" />
      <Panel id="right-panel">{/* ... */}</Panel>
    </PanelGroup>
  );
}
```

**Comment by psychedelicious** [comment]
Ty

**Comment by samesfahani-tuplehealth** [comment]
If Panels are conditionally rendered, then it is possible those refs could be undefined, no?
