### ISSUE TITLE
Type error when I build with resizable

### ISSUE THREAD

**Issue by rhs419** [bvaughn/react-resizable-panels#253]
Type error when I build with resizable in NextJs
I didnt edit anything

![image](https://github.com/bvaughn/react-resizable-panels/assets/73884732/04e2e3a3-fcec-4fa7-b8bf-a411b782b34f)

**Comment by bvaughn** [comment]
I don't know what `ui/resizable` is or what `withHandle` is but I'm guessing you meant to file this bug somewhere else.

**Comment by bvaughn** [comment]
Doing a Google search for "components/ui/resizable" it looks like this is shadcn/ui you're using, so you want to go here: https://github.com/shadcn-ui/ui

**Comment by rhs419** [comment]
Thx :)
