### ISSUE TITLE
Feature Request: Add default values for dom util methods

### ISSUE THREAD

**Issue by psychedelicious** [bvaughn/react-resizable-panels#262]
The util methods in https://github.com/bvaughn/react-resizable-panels/tree/main/packages/react-resizable-panels/src/utils/dom should probably have default values.

Using `document` would retain the previous behaviour, with some minor changes to the types (widening `HTMLElement` to `ParentNode | HTMLElement`.

**Comment by bvaughn** [comment]
This would have been worth doing initially, but I don't know if this change is worth making now that the release has already been made.

**Comment by psychedelicious** [comment]
Wouldn't be surprised if we are the only project that started using these methods before v1.0.8 - likely very minor impact from the breaking change. No worries if you'd like to leave things as-is.

**Comment by bvaughn** [comment]
I'll give it a little thought. :)

**Comment by bvaughn** [comment]
Released in react-resizable-panels@1.0.9

---

❤️ → ☕ [givebrian.coffee](http://givebrian.coffee/)
