### ISSUE TITLE
Feature Request: Double Resize ➡️⬆️

### ISSUE THREAD

**Issue by BrodyRas** [bvaughn/react-resizable-panels#268]
Mimic the behavior of VS Code's panels: place a Double Resize Handle at the intersection of any two panels, allowing the user to resize both panels simultaneously

![double](https://github.com/bvaughn/react-resizable-panels/assets/49171024/17845d1d-c3af-47fb-8777-891ef9199bb6)

**Comment by bvaughn** [comment]
This would require rearchitecting how this library initiates a drag. Might be doable without a lot of work but might require significant changes. If the former I'd be willing to review a PR for it.

**Comment by bvaughn** [comment]
I think I have this working.

https://github.com/bvaughn/react-resizable-panels/assets/29597/6e286fe0-74ec-4160-a057-a0f0f391ac6d

**Comment by lukasbash** [comment]
Epic feature! Would need this too for nested group gutters.

**Comment by bvaughn** [comment]
Made a bit more progress this morning on this. Cursor styles are now accounting for intersecting panels.
[Kapture 2024-01-28 at 12.20.40.webm](https://github.com/bvaughn/react-resizable-panels/assets/29597/01ecede7-8dd1-4979-b65e-9a33b45616a6)

Need to sort out a few more things– mainly, how to update cursors if you've drag too far past a panel's min/max constraints, but I don't think that will be too much work.

**Comment by bvaughn** [comment]
Think I got it!

[Kapture 2024-01-28 at 13.09.26.webm](https://github.com/bvaughn/react-resizable-panels/assets/29597/6e6e138a-9673-47aa-8de0-df1798bc9748)

**Comment by BrodyRas** [comment]
Outstanding work! Thanks so much 😊

**Comment by lukasbash** [comment]
Insane work!! Would be awesome to have this released soon 🤩
