### ISSUE TITLE
Nested PanelGroup flickering when resizing

### ISSUE THREAD

**Issue by vuhuucuong** [bvaughn/react-resizable-panels#27]
I've noticed this border flickering issue when resizing the nested Panel as seen in the below video.
It may be more noticeable on slow machines

https://user-images.githubusercontent.com/26746668/209574615-bb9d989f-be6c-4771-b829-d925281fda2a.mp4

**Comment by bvaughn** [comment]
Fixed via #33

See this comment for an explanation of why https://github.com/bvaughn/react-resizable-panels/issues/32#issuecomment-1365495136
