### ISSUE TITLE
How to control panel collapse?

### ISSUE THREAD

**Issue by n1203** [bvaughn/react-resizable-panels#272]
For example

I want to control the collapse state when double click the element.

![image](https://github.com/bvaughn/react-resizable-panels/assets/30693884/f11b2812-fd2b-4690-8502-31b731022971)

**Comment by n1203** [comment]
thank you @bvaughn 🙏
- this is a good solution: https://github.com/bvaughn/react-resizable-panels/issues/58#issuecomment-1370950761
- demo: https://react-resizable-panels-git-issues-58-bvaughn.vercel.app/examples/imperative-api

**Comment by bvaughn** [comment]
Glad you found it :)

**Comment by Salumsu** [comment]
Hi, how about locking the panel in collapsed mode when in mobile?

**Comment by bvaughn** [comment]
Seems like something you could do with props (default/min/max size) that you pass conditionally based on user agent.
