### ISSUE TITLE
[Enhancement] Support CSS values for defaultSize, maxSize & minSize 

### ISSUE THREAD

**Issue by 11xdeveloper** [bvaughn/react-resizable-panels#277]
### e.g.
```tsx
// ...
<Panel
    defaultSize='10svw'
    {/* ... */}
>
// ...
```

Much more convenient not having to use window.innerWidth / window.innerHeight.

As well as more accurate when it comes to newer values such as dvw, dvh, swv, svh, etc.

**Comment by bvaughn** [comment]
Panel size constraints are exclusively percentages. No CSS unites– pixel or otherwise– are supported.

The [FAQ](https://github.com/bvaughn/react-resizable-panels?tab=readme-ov-file#can-panel-sizes-be-specified-in-pixels) mentions this:
> ### Can panel sizes be specified in pixels?
> 
> No. Pixel-based constraints [added significant complexity](https://github.com/bvaughn/react-resizable-panels/pull/176) to the initialization and validation logic and so I've decided not to support them. You may be able to implement a version of this yourself following [a pattern like this](https://github.com/bvaughn/react-resizable-panels/issues/46#issuecomment-1368108416) but it is not officially supported by this library.
