### ISSUE TITLE
How to change minimum size to collapse the panel

### ISSUE THREAD

**Issue by arpitBhalla** [bvaughn/react-resizable-panels#283]
Right now, when I drag the handle to ~50% it collapses, is there any way to increase this?

**Comment by bvaughn** [comment]
I'll take a stab at this question:
> How to change minimum size to collapse the panel

You specify the panel's minimum, non-collapsed size (`minSize`) and it collapses whenever you resize it to less than 50% of that minimum size, as you see here:
https://github.com/bvaughn/react-resizable-panels/assets/29597/54b640f9-325a-4f56-817e-95af8aa7c7a2

I'm going to close this as answered. If you have a follow up question though, feel free.

**Comment by arpitBhalla** [comment]
Yes, is there any way to change 50% to anyone other fraction?

**Comment by bvaughn** [comment]
No. That's not supported.
