### ISSUE TITLE
[Example]: Conditional and Collapsible Panels

### ISSUE THREAD

**Issue by digoburigo** [bvaughn/react-resizable-panels#284]
I'm trying to use these both features together and I think it's not behaving the way I thought would be.

For example, when both left and right panels are showing and collapsed and then I hide one of them, the other panel it's going to expand instead of being collapsed.

Is this the expected behavior? Or how do I change this to keep the collapsed panels collapsed? 

Reproduction: https://stackblitz.com/edit/stackblitz-starters-rftqoi?file=src%2FApp.tsx

**Comment by bvaughn** [comment]
Sorry but I'm not sure what you're describing.

**Comment by digoburigo** [comment]
In the reproduction example, if both panels are showing and collapsed, if I hide the left panel, the right panel it's going to expand instead of being collapsed. Is this the expected behavior?

**Comment by bvaughn** [comment]
> In the reproduction example, if both panels are showing and collapsed, if I hide the left panel, the right panel

If both panels are collapsed, then how can you hide the only remaining panel? This is what I don't understand about the original description.

**Comment by digoburigo** [comment]
I have the state of both `left` and `right` panels collpsed and showing, like in the image below:
![image](https://github.com/bvaughn/react-resizable-panels/assets/28462822/0c31b727-471d-4ad4-aa5d-b5675840ec2e)

When I hide the `left` panel, for example, instead of the `right` panel remain collapsed and the `middle` occupy all the space, the opposite occurs, the `right` panel uncollapse like in the image below:
![image](https://github.com/bvaughn/react-resizable-panels/assets/28462822/71ae13f6-3b26-4262-9adf-41abc7b8a99e)

My point is that I think the `middle` panel would fill in the space and the `right` panel would remain collapsed. Is this more clear?

**Comment by digoburigo** [comment]
Tried this on the reproduction and not seems to work
![image](https://github.com/bvaughn/react-resizable-panels/assets/28462822/29a4ef94-29f1-4a92-8fd5-9d1929842605)

![image](https://github.com/bvaughn/react-resizable-panels/assets/28462822/76257fe1-a52c-434b-a743-3f1e5f60a745)

**Comment by bvaughn** [comment]
I can't really help with screenshots, mate. There's nothing to debug.

I think at this point, it would be easiest for me if you sent a [Replay of what you're seeing](https://www.replay.io/) so I can look at it exactly. Barring that, send an updated Code Sandbox or something.

**Comment by bvaughn** [comment]
If you have a group with two (or more) possible layouts, the _default_ layout as well as the _saved_ layout are initialized and stored separately for each combination of panels. (This is necessary for reasons I tried to explain in #260.)

If you want the layout to appear to stay the same between different panel combinations, then either you need to (a) use the imperative API to set it yourself after conditionally rendering a different set of panels or (b) use an approach like I mentioned above to hide a panel without conditionally rendering it.

**Comment by digoburigo** [comment]
Ok. I got it now.

I will test with the imperative API to achieve what I want. 

Thanks for the time to explain how the state works and thanks for this amazing library.

**Comment by bvaughn** [comment]
You're welcome 😄  Good luck!
