### ISSUE TITLE
Can I use conditional rendering with imperative group panel API?

### ISSUE THREAD

**Issue by alissa-tung** [bvaughn/react-resizable-panels#285]
In addition, I am using a version wrapped by https://ui.shadcn.com/ , and I had add the https://github.com/shadcn-ui/ui/pull/2699 support

updated: i had tested on the raw version of this library, still not work too

here the terms conditional rendering refers to https://react-resizable-panels.vercel.app/examples/conditional , and imperative group panel API refers to https://react-resizable-panels.vercel.app/examples/imperative-panel-group-api .

I had done a lot of test, when using something like

```tsx
    <ResizablePanelGroup
      direction="horizontal"
      ref={colImperativePanelGroupHandle}
    >
      {layoutState.layoutColumnTwoLeftButtonFocusState ? <></> : leftPanel}
      <ResizablePanel id="main-panel" order={2}>
        {editorDiv}
      </ResizablePanel>
      {layoutState.layoutColumnTwoRightButtonFocusState ? <></> : rightPanel}
    </ResizablePanelGroup>
```

and the `setLayout` is from

```ts
  const leftPanelSize = !layoutState.layoutColumnTwoLeftButtonFocusState
    ? layoutState.leftPanelSize
    : 0;
  const rightPanelSize = !layoutState.layoutColumnTwoRightButtonFocusState
    ? layoutState.rightPanelSize
    : 0;
  const mainPanelSize = 100 - leftPanelSize - rightPanelSize;
  return [leftPanelSize, mainPanelSize, rightPanelSize].filter((x) => x !== 0);
```

the layout does not respect to the value of `getLayout()` after `setLayout`.

but just not use conditional render `{?:}`, instead of set the panel size to zero (without filtering the list) makes the layout seems normal, except there is a 0 width panel and 1 width panel handle.

**Comment by bvaughn** [comment]
> Can I use conditional rendering with imperative group panel API?

No. The concept of conditional rendering is that sometimes you render a panel, and sometimes you don't. In order to use the imperative API, the panel must be rendered (even if it's collapsed).

> but just not use conditional render {?:}, instead of set the panel size to zero (without filtering the list) makes the layout seems normal, except there is a 0 width panel and 1 width panel handle.

Yes. I suggest you just conditionally render them. There isn't really enough info in this issue for me to understand why that isn't sufficient.

**Comment by bvaughn** [comment]
Nice! Glad you got it figured out 😄  Take care!

---

❤️ → ☕ [givebrian.coffee](http://givebrian.coffee/)
