### ISSUE TITLE
onDragging to much calls

### ISSUE THREAD

**Issue by damaafer** [bvaughn/react-resizable-panels#287]
Does I misuse PanelResizeHandle's onDragging prop ?

Excepted behavior:
onDragging is only call when it's PanelResizeHandle is effectively dragged.

Actual behavior:
Any click anywhere on the page triggers onDragging callback of every PanelResizeHandle.

Repro: https://codesandbox.io/p/sandbox/react-resizable-panels-forked-t6cmkx
(open the console and click anywhere on the page).

**Comment by bvaughn** [comment]
This is a bug. Will try to release a fix shortly.

**Comment by bvaughn** [comment]
Fixed in 5afa01c and 6c74960; released in version 2.0.4

---

❤️ → ☕ [givebrian.coffee](http://givebrian.coffee/)

**Comment by damaafer** [comment]
Works great. Thank you for the quick fix 👍

**Comment by paulm17** [comment]
Not sure if it's the same issue or a new one.

OnDragging doesn't do anything.  But if you mouseover it triggers the onDragging event.
