### ISSUE TITLE
Z Index issues

### ISSUE THREAD

**Issue by websiddu** [bvaughn/react-resizable-panels#288]
I'm able to access the resize handle above a dialog or anything above the resize handle. 

I tried a bunch of z-index changes, but nothing worked, is there a way to disable the resize highlight when a dialog is over the resize line? 

Demo 
![Area](https://github.com/bvaughn/react-resizable-panels/assets/968912/773d2ff8-1add-486f-943c-87af366688fd)

Reproduction link 
https://codesandbox.io/p/devbox/clever-johnson-yl7sg4?workspaceId=3494ce51-f0e3-4621-b467-08e9f6142c44

**Comment by bvaughn** [comment]
Yeah, I think this is a bug in the recent `PanelResizeHandleRegistry` utility I wrote, to support resizing multiple panels at once. Will need to think about how best to handle z-index.

**Comment by bvaughn** [comment]
This is trickier than I had hoped.

I have a work in progress attempt on #291 but (a) I'm not sure how expensive calculating and comparing stacking order will be and (b) I'm not yet sure why the change breaks my e2e tests.

**Comment by bvaughn** [comment]
Fixed in c1aa2b0; available in version 2.0.5

---

❤️ → ☕ [givebrian.coffee](http://givebrian.coffee/)
