### ISSUE TITLE
Resizing panels should not require a full re-render

### ISSUE THREAD

**Issue by bvaughn** [bvaughn/react-resizable-panels#29]
Resizing a panel should just be a matter of changing the `style` value, which could be done _imperatively_ (without requiring a re-render). This has some consequences, since rendering that's conditional on size would not "work" with a partially imperative UI, but the way panel sizes are being managed (as `CSSProperties` objects) is somewhat opaque already so this change would probably be okay.

Related: #27

**Comment by bvaughn** [comment]
Hey @shshaw! Thanks for sharing! 😁

That's an interesting option too. I had been thinking of just imperatively updating the `flexGrow` style but what you mention is probably a bit cleaner. Worth thinking about!

**Comment by albert-schilling** [comment]
@bvaughn First, thanks for the great library!

I would add that avoiding too many rerenderings is not the only target, **also avoiding to many redraws**. I just added your lib in a dashboard that splits a chart and a table, each displaying large amounts of data. The chart needs to rerender and redraw on size changes which is quite costly. Thus, I had to wrap the Panel component with some logic to debounce redraws.

I believe it would make sense, if a `Panel` would consist of two layered components. The outer component would immediately update its CSS on resizing, while its child, the inner component, would react to size changes with a given delay. 
As far as I understand, in your implementation, you rely on each panel to immediately update its size to properly reposition the `PanelResizeHandle` component which is also just a flex item. Thus, you would need two layered components to implement this kind of debouncing. 

It would be great if the lib would offer an API to specify a debounce delay.

Another thought: I think it would be very ergonomic for users, if you would expose the internal context, like `usePanelsGroupContext` or `usePanelsContext`. This would speed up extending/building around the lib. I understand you can do all that with the `onResize` and `onDragging` callbacks or the imperative handles, but directly reading from the contexts would be very ergonomic.

**Comment by bvaughn** [comment]
RE: Debouncing – I think what you're describing makes the most sense to do at the application level. (I don't think "render debouncing" is very common for React applications, and I think it's something that would be pretty easy to add on a per-component basis if you have something that's a heavy render.)

RE: Contexts – I understand what you're saying– but the context is intentionally private, because the methods on it are not meant to be used externally. (The ones that are get exported.) Keeping a project's internals _internal_ is an important part of being able to maintain and change it going forward.

**Comment by albert-schilling** [comment]
Thank you for the quick reply.

I agree with both your responses. 
Regarding Contexts: I did not mean exposing the library's internals but rather adding a "public" context to improve dev. ergonomics. Being able to access a panel's context anywhere inside a `Panel` or `PanelGroup` would be cool.

**Comment by bvaughn** [comment]
I don't think this is a change I want to make.

**Comment by Criezc** [comment]
I'm encountering the same issues, any update on this issues? @bvaughn thanks before!
