### ISSUE TITLE
panel seems to get clipped when dragging up

### ISSUE THREAD

**Issue by TheBuilderJR** [bvaughn/react-resizable-panels#290]
It's quite an interesting bug. It gets clipped when dragging up but then gets unclipped when dragging down.

Here's a video of the bug:

https://github.com/bvaughn/react-resizable-panels/assets/46176773/dc6c6c7d-a1e1-4840-bbb1-8e844ede6c67

Here's my code

```
import Editor from "@monaco-editor/react";
import { Theme, useTheme } from "remix-themes";
import { Button } from "./ui/button";

export default function Component() {
  const [theme, setTheme] = useTheme();
  const editorTheme = theme === Theme.DARK ? "vs-dark" : "vs-light";

  return (
    <div className="flex flex-col h-full space-y-1">
      <Editor
        className="w-full h-full"
        defaultLanguage="sql"
        defaultValue="SELECT * FROM my_table LIMIT 10;"
        theme={editorTheme}
        options={{
          minimap: {
            enabled: false,
          },
        }}
      />
      <div className="flex items-center justify-end mr-3 justify-endspace-x-2">
        <Button>Submit</Button>
      </div>
    </div>
  );
}
```

**Comment by bvaughn** [comment]
Please share a full repro that I can run. Partial code isn't enough. The issue could be a bug with your CSS styling.

**Comment by TheBuilderJR** [comment]
Let me see if I can extract this out into a code sandbox. In the meantime here's the actual parent panel code in case it rings any bells

```
import { CommandMenu } from "~/components/command-menu";
import Editor from "~/components/editor";
import { MobileNav } from "~/components/mobile-nav";
import { ModeToggle } from "~/components/mode-toggle";
import {
  ResizableHandle,
  ResizablePanel,
  ResizablePanelGroup,
} from "~/components/ui/resizable";

const Content = () => (
  <ResizablePanel defaultSize={50}>
    <ResizablePanelGroup direction="vertical">
      <ResizablePanel defaultSize={25}>
        <Editor />
      </ResizablePanel>
      <ResizableHandle withHandle />
      <ResizablePanel defaultSize={75}>
        <div className="flex items-center justify-center h-full p-6">
          <span className="font-semibold">Three</span>
        </div>
      </ResizablePanel>
    </ResizablePanelGroup>
  </ResizablePanel>
);

export default function Team() {
  return (
    <div className="flex flex-col h-screen">
      <div className="hidden h-full sm:block">
        <ResizablePanelGroup
          direction="horizontal"
          className="items-stretch w-full"
          onLayout={(sizes: number[]) => {
            document.cookie = `react-resizable-panels:layout=${JSON.stringify(
              sizes
            )}`;
          }}
        >
          <ResizablePanel
            defaultSize={20}
            minSize={15}
            collapsible={true}
            maxSize={20}
          >
            <div className="flex h-[200px] items-center justify-center p-6">
              <span className="font-semibold">One</span>
            </div>
          </ResizablePanel>
          <ResizableHandle withHandle />
          <Content />
        </ResizablePanelGroup>
      </div>
      <div className="h-full sm:hidden">
        <div className="container flex items-center h-14 max-w-screen-2xl">
          <MobileNav />
          <div className="flex items-center justify-between flex-1 space-x-2 md:justify-end">
            <div className="flex-1 w-full md:w-auto md:flex-none">
              <CommandMenu />
            </div>
            <nav className="flex items-center">
              <ModeToggle />
            </nav>
          </div>
        </div>
        <ResizablePanelGroup
          direction="horizontal"
          className="items-stretch w-full"
          onLayout={(sizes: number[]) => {
            document.cookie = `react-resizable-panels:layout=${JSON.stringify(
              sizes
            )}`;
          }}
        >
          <Content />
        </ResizablePanelGroup>
      </div>
    </div>
  );
}
```

**Comment by TheBuilderJR** [comment]
ok here you go, drag the top panel down and back up and notice the button gets hidden

https://codesandbox.io/p/sandbox/react-resizable-panels-forked-9cjsgy?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clsgbggwm00063b6ej470h6bt%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clsgbggwm00023b6evu49budj%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clsgbggwm00033b6e6r1y09cz%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clsgbggwm00053b6e7i08lau0%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clsgbggwm00023b6evu49budj%2522%253A%257B%2522id%2522%253A%2522clsgbggwm00023b6evu49budj%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsgbheqk004j3b6ey5r6yirs%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A2%252C%2522startColumn%2522%253A60%252C%2522endLineNumber%2522%253A2%252C%2522endColumn%2522%253A60%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clsgbheqk004j3b6ey5r6yirs%2522%257D%252C%2522clsgbggwm00053b6e7i08lau0%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsgbggwm00043b6euubj3bat%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clsgbggwm00053b6e7i08lau0%2522%252C%2522activeTabId%2522%253A%2522clsgbggwm00043b6euubj3bat%2522%257D%252C%2522clsgbggwm00033b6e6r1y09cz%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clsgbggwm00033b6e6r1y09cz%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

**Comment by bvaughn** [comment]
> Sandbox not found

**Comment by TheBuilderJR** [comment]
sorry about that - first time using code sandbox to share a repro. here's a public link

https://codesandbox.io/p/sandbox/react-resizable-panels-forked-9cjsgy?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clsgbggwm00063b6ej470h6bt%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clsgbggwm00023b6evu49budj%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clsgbggwm00033b6e6r1y09cz%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clsgbggwm00053b6e7i08lau0%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clsgbggwm00023b6evu49budj%2522%253A%257B%2522id%2522%253A%2522clsgbggwm00023b6evu49budj%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsgbheqk004j3b6ey5r6yirs%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A2%252C%2522startColumn%2522%253A60%252C%2522endLineNumber%2522%253A2%252C%2522endColumn%2522%253A60%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clsgbheqk004j3b6ey5r6yirs%2522%257D%252C%2522clsgbggwm00053b6e7i08lau0%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsgbggwm00043b6euubj3bat%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clsgbggwm00053b6e7i08lau0%2522%252C%2522activeTabId%2522%253A%2522clsgbggwm00043b6euubj3bat%2522%257D%252C%2522clsgbggwm00033b6e6r1y09cz%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clsgbggwm00033b6e6r1y09cz%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

**Comment by bvaughn** [comment]
This is a Flex/CSS overflow issue. You can't reproduce it by resizing the browser window to be shorter without even using this library.

To fix it, add `overflow: hidden` to the `<section>` element.

**Comment by TheBuilderJR** [comment]
perfecto! thank you!

for future readers of this issue, you can simply add the overflow-hidden class on the <Editor component and it'll add it to the section element as @bvaughn suggested
