### ISSUE TITLE
[Enhancement] Provide "null" storage to avoid persistence in localstorage

### ISSUE THREAD

**Issue by lukasbash** [bvaughn/react-resizable-panels#302]
Right now we have to pass a custom crafted null-ish storage to avoid local storage persistence:
```typescript
export const nullPanelStorage: PanelGroupStorage = {
  getItem: () => null,
  setItem: () => {},
};
```

It would be awesome if we could just pass `null` as a storage or even get a boolean flag for disabling the persistence at all.

**Comment by bvaughn** [comment]
> Right now we have to pass a custom crafted null-ish storage to avoid local storage persistence

That is the default behavior you're describing. Don't specify an `autoSaveId` prop and the panel won't save anything to local storage.
