### ISSUE TITLE
Assertion Failed on conditionally rendered panels with size constraints

### ISSUE THREAD

**Issue by DenizUgur** [bvaughn/react-resizable-panels#303]
Hi @bvaughn, first of all thank you for this amazing library. It has been a core feature for my project. In my project, I'm using resizable panels dynamically. As in, there are a set of layouts with size constraints defined in them as well. When I switch between layouts I get an assertion error. I've found out this is due to `minSize` and `maxSize` being supplied. Most probably I'm not using them as they should so I would love it if you could shine a light on this.

Here is a repro: https://codesandbox.io/p/sandbox/youthful-jennings-wt9ffk

**Comment by bvaughn** [comment]
Thanks for the repro. I will try to take a look sometime soon.

**Comment by DenizUgur** [comment]
Okay found the problem, my outermost panel group had the same id despite the layout's change. Replacing it with unique ID or `crypto.randomUUID()` solved the problem. This didn't worked for the sandbox demo I've sent though.

Possibly a check for duplicate id's across re-render could be implemented?

**Comment by bvaughn** [comment]
That's interesting. Even with the same id, layouts should be stored uniquely based on the group id _and_ the combination of panel constraints (so if you conditionally rendered panels, they don't clobber each others layouts).

Would you be able to reduce your repro to a failing unit test (in this repo)? That would help me fix it.

**Comment by DenizUgur** [comment]
Let me try to do that. I'll try open a PR today

**Comment by bvaughn** [comment]
Thank you! That would be super helpful.

**Comment by DenizUgur** [comment]
[Solution](https://github.com/bvaughn/react-resizable-panels/pull/307#issuecomment-1962434364) was found in the PR

**Comment by bvaughn** [comment]
Fix published in 2.0.10
