### ISSUE TITLE
Panel becomes unresizable after a certain vertical position in the page

### ISSUE THREAD

**Issue by Specy** [bvaughn/react-resizable-panels#305]
For some reason after reaching a certain position on the vertical axis (seems to be after 100vh?) the resize handle stops working, i made an example here:
[sandbox example](https://codesandbox.io/p/sandbox/strange-snowflake-f9r8s7)

I'm using v2.0.9 of the library 

It doesn't seem to happen in v1.0.10
It seems to originate from v2.0.0, any version after v2 has this issue

**Comment by bvaughn** [comment]
Thanks for the repro. I will try to take a look sometime soon.

**Comment by Specy** [comment]
Sure thing! In the meanwhile I'm using v1.0.10 which seems to be working fine

**Comment by bvaughn** [comment]
Should be fixed in react-resizable-panels@2.0.11
---

❤️ → ☕ [givebrian.coffee](http://givebrian.coffee/)

**Comment by Specy** [comment]
Thank you! I'll test tomorrow
