### ISSUE TITLE
Strange behaviour when resizing with nested panels

### ISSUE THREAD

**Issue by dr3** [bvaughn/react-resizable-panels#32]
When using nested panels https://react-resizable-panels.vercel.app/examples/nested there appears to be some strange behaviour that lets certain panels escape their boundry

https://user-images.githubusercontent.com/11341355/209586617-e86ecf0c-cfb1-4c87-9555-3dd56f07af20.mov

E.g.
<img width="340" alt="image" src="https://user-images.githubusercontent.com/11341355/209586635-c550be01-530a-48ab-9286-549a85c4ec79.png">
<img width="268" alt="image" src="https://user-images.githubusercontent.com/11341355/209586651-f1e66216-39be-4179-969e-7df914fd19d7.png">

**Comment by bvaughn** [comment]
I think this has to do with a combination of factors:
* `PanelGroup` is currently using absolute positions for panels and so–
* If rendering (or even imperative resizing) isn't fast enough, nested panel sizes _lag_

Issue #29 _might_ help with this a little but I think #30 might be a better fix.

**Comment by bvaughn** [comment]
Yeah, #30 fixes this really nicely. I'll probably push it out tomorrow morning, after some more testing.

**Comment by bvaughn** [comment]
PR #33 has the work in progress here.

You can test it out here:
https://react-resizable-panels-git-issues-30-bvaughn.vercel.app/examples/nested

**Comment by bvaughn** [comment]
#33
