### ISSUE TITLE
Programmably resize panel

### ISSUE THREAD

**Issue by jpainam** [bvaughn/react-resizable-panels#320]
Hi.
I can listen to size changes with `onExpand` and with `onCollapse`, but I can't find a way to set the size of a panel programmably.
I would like to programmbly set the panel size on user clicked.

Thanks.

**Comment by bvaughn** [comment]
Have you read the docs?

panelRef.resize() does exactly what you’re asking

https://react-resizable-panels.vercel.app/examples/imperative-panel-api

---

❤️ → ☕ [givebrian.coffee](http://givebrian.coffee/)
