### ISSUE TITLE
Flickering when using three panels

### ISSUE THREAD

**Issue by julianZeitler** [bvaughn/react-resizable-panels#322]
I am using three horizontally aligned panels. There is some flickering occurring on the right panel whenever I resize with the left handle. I tried to fix this by saving the layout with a cookie as is mentioned in the documentation, but that doesn't seem to fix it. This issue occurs regardless of whether I use client or server components. I set up a
[codesanbox](https://codesandbox.io/p/sandbox/jolly-turing-m482nz?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clty8j5ov00062v6be0k77sq6%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clty8j5ov00022v6bmy6zeg26%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clty8j5ov00032v6big37opiq%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clty8j5ov00052v6bpev3ynbe%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B64.4069582543058%252C35.593041745694194%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clty8j5ov00022v6bmy6zeg26%2522%253A%257B%2522id%2522%253A%2522clty8j5ov00022v6bmy6zeg26%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clty8j5ov00052v6bpev3ynbe%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clty8j5ov00042v6b1zb5vgo5%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clty8j5ov00052v6bpev3ynbe%2522%252C%2522activeTabId%2522%253A%2522clty8j5ov00042v6b1zb5vgo5%2522%257D%252C%2522clty8j5ov00032v6big37opiq%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clty8j5ov00032v6big37opiq%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) as an example using only client components. The flickering occurs only on some positions of the right handle. I noticed, that this effect is not present in versions 0.0.55 and below. 

Locally I set up an example with a server component as in the documentation. Here this issue is also arising. I a am using version 12.0.13 in this example.

Server component:
```TypeScript
import { cookies } from "next/headers";
import ClientComponent from "./ClientComponent";


export default function Home() {
  const layout = cookies().get("react-resizable-panels:layout");

  let defaultLayout;
  if (layout) {
    defaultLayout = JSON.parse(layout.value);
  }

  return <ClientComponent defaultLayout={defaultLayout} />;
}
```
Client component:
```TypeScript
"use client";

import { Panel, PanelGroup, PanelResizeHandle } from "react-resizable-panels";

export default function ClientComponent({
  defaultLayout = [30, 40, 30],
}: {
  defaultLayout: number[] | undefined;
}) {
  const onLayout = (sizes: number[]) => {
    document.cookie = `react-resizable-panels:layout=${JSON.stringify(sizes)}`;
  };

  return (
    <PanelGroup direction="horizontal" onLayout={onLayout}>
      <Panel
        className="bg-slate-100 rounded-lg flex items-center justify-center text-center p-2"
        defaultSize={30}
        minSize={10}
      >
        Left panel
      </Panel>
      <PanelResizeHandle className="mx-1 w-2 bg-slate-300" />
      <Panel
        className="bg-slate-100 rounded-lg flex items-center justify-center text-center p-2"
        defaultSize={30}
        minSize={10}
      >
        Middle panel
      </Panel>
      <PanelResizeHandle className="mx-1 w-2 bg-slate-300" />
      <Panel
        className="bg-slate-100 rounded-lg flex items-center justify-center text-center p-2"
        defaultSize={40}
        minSize={10}
      >
        Right panel
      </Panel>
    </PanelGroup>
  );
}
```

**Comment by bvaughn** [comment]
This seems like it's probably the same issue as #323 so let's go ahead and merge this issue with that one.
