### ISSUE TITLE
Feature Request: Size stepping

### ISSUE THREAD

**Issue by garrettg123** [bvaughn/react-resizable-panels#324]
I'm not sure if this is possible, but is it possible to require a step size? For example, for a step size of 10, until I drag from size 20 to 25, it doesn't show the next step (30).

Great work!

**Comment by bvaughn** [comment]
I think that would be _possible_ to implement, but I have some reservations about the UX. (I think it might feel kind of broken/unresponsive?) Realistically, this isn’t a feature that I have the time to build and maintain.

If you’d like to fork and add this feature I could give a few pointers/suggestions on how you might go about it though.

Thanks for understanding 🙇

**Comment by paulm17** [comment]
I have a requirement to step in 2px increments.  When you have some time, can you please get into the details on how to achieve this?  I have already forked the project internally in my monorepo and thus can make changes pretty easily!  Thanks!
