### ISSUE TITLE
minSizePercentage and minSizePixels Attributes Trigger Excessive Reflows

### ISSUE THREAD

**Issue by in-ch** [bvaughn/react-resizable-panels#337]
Thank you so much for the good library. I'm reporting on one issue.

When applying the minSizePercentage and minSizePixels attributes, each movement of the panel from end to end (when reaching the minimum size) triggers excessive reflows. 

Reflows occurred at the areas highlighted in red in the attached image. This leads to frame drops, causing performance issues.

### Before Applying minSizePercentage or minSizePixels
![최적화3](https://github.com/bvaughn/react-resizable-panels/assets/49556566/7f570ec6-c30a-431d-886a-bd99a988775e)

### After Applying minSizePercentage or minSizePixels
![최적화전](https://github.com/bvaughn/react-resizable-panels/assets/49556566/16f9280c-964c-498d-bd37-0bcade6d3cde)

**Comment by bvaughn** [comment]
I don’t see where you specified the version, but given the description of this issue it seems like you’re using an older version of this library. I don’t have the time to support older versions unfortunately. I suggest you update to the latest version for bug fixes, or if you can’t do that- I suggest you fork and try to fix the issue. If you want to submit a PR, I might be able to review and do a one off release but only if it’s small. (Sorry. This is a side project and I don’t have a lot of free time now.)

thank you for understanding 🙇 and thank you for the kind words

**Comment by in-ch** [comment]
Thank you. 😃

It turns out it was indeed a version issue. 
After updating the version, all the problems were resolved.

 I appreciate your kindness. Have a great day. 🙇
