### ISSUE TITLE
Still resizes after releasing mouse outside window

### ISSUE THREAD

**Issue by Fabioni** [bvaughn/react-resizable-panels#340]
Check out the sandbox: https://codesandbox.io/p/sandbox/react-resizable-panels-forked-r6zcm6

If you drag the resizer up until the first panel gets collapsed, and you release the mouse outside the iframe of codesandbox (or just outside your browser window) your code does not recognize the mouse release and still changes the panel size after the mouse hovers back over the iframe.

**Comment by bvaughn** [comment]
If you'd like to post a PR for this, I'll try to make the time to review it. Else I probably won't have the time to pick it up.

**Comment by afshawnlotfi** [comment]
Having the same issue

**Comment by bvaughn** [comment]
I think the iframe in Code Sandbox is causing this behavior. Seems like the "pointerup" event isn't being registered if it's fired outside of the iframe. Maybe something is intercepting and canceling the event? Not sure.

**Comment by bvaughn** [comment]
I think I've found a fix in #374

**Comment by bvaughn** [comment]
Fixed in #374

---

❤️ → ☕ [givebrian.coffee](http://givebrian.coffee/)
