### ISSUE TITLE
Resize behaviour breaks if PanelResizeHandle rerenders during resizing

### ISSUE THREAD

**Issue by Fabioni** [bvaughn/react-resizable-panels#342]
Please check that sandbox. The problem is in the comments:

https://codesandbox.io/p/sandbox/react-resizable-panels-forked-tz8mc5

It is one of the typical React nightmares. Having the following in the code rerenders `PanelResizeHandle` every time the parent rerenders because the prop referentially changes. 

```jsx
<PanelResizeHandle
    hitAreaMargins={{ coarse: x, fine: y }} // this triggers rerender of PanelResizeHandle
/>
```

Together with `setIsCollapsed(true)` which triggers a rerender of the parent, this **breakes the mouse logic of panel resize**. Collapse and Expand in the sandbox and you will know what I mean.

```jsx
const [isCollapsed, setIsCollapsed] = useState(false);

  return (
    <PanelGroup direction="horizontal">
      <Panel
        onCollapse={() => setIsCollapsed(true)}
      </Panel>
    </PanelGroup>
)
```

All together:

```jsx
export default function App() {
  const [isCollapsed, setIsCollapsed] = useState(false);

  return (
    <PanelGroup direction="horizontal">
      <Panel
        minSize={30}
        collapsible
        collapsedSize={10}
        onCollapse={() => setIsCollapsed(true)} // this triggers rerender of App
        onExpand={() => setIsCollapsed(false)} // this triggers rerender of App
        style={{ backgroundColor: "red" }}
      ></Panel>
      <PanelResizeHandle
        style={{ flex: "0 0 20px" }} // this triggers rerender of PanelResizeHandle
        hitAreaMargins={{ coarse: 15, fine: 5 }} // this triggers rerender of PanelResizeHandle
      />

      <Panel minSize={30} style={{ backgroundColor: "orange" }}></Panel>
    </PanelGroup>
  );
}

// using this would prevent from rerendering PanelResizeHandle
const savepropsstyle = { flex: "0 0 20px" };
const savepropsare = { coarse: 15, fine: 5 };

```

**Comment by bvaughn** [comment]
FWIW, the inline `style` prop is not related to the issue you're reporting. Only the inline `hitAreaMargins` is because the `PanelResizeHandle` re-initializes itself whenever that object changes. I can refine that logic a bit to extract the fine and coarse values, so that it only re-initializes itself when those change though.
