### ISSUE TITLE
Add option to reset React-Resizable-Pane to default size on external button click

### ISSUE THREAD

**Issue by SagarDhyani** [bvaughn/react-resizable-panels#344]
Is there any existing functionality or workaround in React-Resizable-Pane that allows resetting the pane to its default size upon clicking a button outside the component? If not, could this feature be considered for implementation?

We believe this feature would greatly enhance user experience by providing a convenient way to reset the resizable pane without directly interacting with it.

**Comment by bvaughn** [comment]
Application code assigns the default size and application code can use the imperative [`setLayout`](https://react-resizable-panels.vercel.app/examples/imperative-panel-group-api) or [`resize`](https://react-resizable-panels.vercel.app/examples/imperative-panel-api) APIs to reset to default size. Shouldn't require any changes from this library. :)
