### ISSUE TITLE
Active resize handle styling

### ISSUE THREAD

**Issue by jyash97** [bvaughn/react-resizable-panels#36]
If you use the website in Mobile and try resizing panels you will notice that the active styles are not triggered, on debugging I found that on the web it focuses on the handle but in Mobile, the focus is only added if we click the handle but if we start moving it doesn't focus on the handle. 

Maybe we can add a data attribute called `data-panel-active=true` whenever the handle is active and is being dragged. As of now we need to add focus styles for the active handle.

I am open to helping on this issue :D

Reproducible steps:
https://user-images.githubusercontent.com/22376783/209684416-e780f949-4a5d-4008-8c66-09fd61a2c109.mov

**Comment by bvaughn** [comment]
On an actual mobile device, the active styles are triggered (at least based on my testing). I _think_ what your video appears to be showing is a "fake" mobile scenario where a drag handle has been tab-focused and then a fake "touch" (click) is dragging a different handle. Can you confirm?

**Comment by bvaughn** [comment]
> Maybe we can add a data attribute called `data-panel-active=true` whenever the handle is active and is being dragged. As of now we need to add focus styles for the active handle.

This is an interesting suggestion.

**Comment by jyash97** [comment]
Yes I reproduced the issue in my mobile first, sharing the mobile screen recording. 

https://user-images.githubusercontent.com/22376783/209685160-372890e3-1947-41e3-8176-12fdc436f2c4.mp4

**Comment by jyash97** [comment]
Here's another example, I removed `isDragging` condition for styles and the styles are still applied because the focus is trapped to resize handle. So as of now we always have to add focus styles to make sure active styles works. We can't differentiate between active styles and focus styles unless we pass custom ids always

**Comment by bvaughn** [comment]
@jyash97 Interesting. Are you using an Android? I don't have one of those to test with unfortunately 😢

**Comment by jyash97** [comment]
Yes I am the video was from an Android device. But still we cant differentiate active and focus styles

**Comment by bvaughn** [comment]
> But still we cant differentiate active and focus styles

Yes, I understand that. I'm just trying to better understand which devices it impacts 😄 

> Maybe we can add a data attribute called `data-panel-active=true`

Would this change fix the issue you're seeing?

**Comment by jyash97** [comment]
>Yes, I understand that. I'm just trying to better understand which devices it impacts 😄

Sorry, I thought you might have missed it. 

> Would this change fix the issue you're seeing?

Yes I think so, do you want me to draft a PR ? I can do this within next hour or so

**Comment by bvaughn** [comment]
> Yes I think so, do you want me to draft a PR ? I can do this within next hour or so

Very kind of you to offer!

I've already got a branch locally to test that change. I like it (even separately from this issue) since it removes the awkward `useContext` usage in favor of pure CSS 😄

**Comment by bvaughn** [comment]
@jyash97 Can you test it out for me?

https://react-resizable-panels-git-issues-36-bvaughn.vercel.app/

**Comment by bvaughn** [comment]
Great! Thank you 🙇🏼

**Comment by jyash97** [comment]
>I've already got a branch locally to test that change. I like it (even separately from this issue) since it removes the awkward useContext usage in favor of pure CSS 😄

Yeah it's easy to style now. Thanks for the quick fix, I was just testing it around and glad the solution helped :D
