### ISSUE TITLE
Handle Father Panel size inside nested Panel Group 

### ISSUE THREAD

**Issue by ItsTonyDavid** [bvaughn/react-resizable-panels#362]
I was doing some nested panels. But I needed to handle the father's panel size inside the nested Panel Group.

```
<PanelGroup direction="horizontal">
  <Panel>
  {/* Stuff in here */}
  </Panel>
  <Panel id="father"> 
    <PanelGroup direction="vertical">
      <Panel id={child}>
      </Panel>
      <PanelResizeHandle/>
      <Panel id={child}>
      </Panel>
    </PanelGroup>
  </Panel>
</PanelGroup>
```

Could the Panel with ID child handle the resize of the father panel too?

**Comment by bvaughn** [comment]
You can do this using the panel group `onLayout` prop _or_ the panel `onResize` prop. (You can listen to size changes and pass them down as props or context to your nested components.)
