### ISSUE TITLE
Issue with Cursor Icon Behavior in Nested Panels Example

### ISSUE THREAD

**Issue by benishouga** [bvaughn/react-resizable-panels#378]
Issue with Cursor Icon Behavior in Nested Panels Example
Example Link: https://react-resizable-panels.vercel.app/examples/nested

### Description:

I have noticed an issue with the cursor icon behavior in the nested panels example on your site.

- **Expected Behavior**: When hovering over a `PanelResizeHandle`, the cursor icon should change to indicate the direction in which the panel can be resized.
- **Actual Behavior**: After dragging vertically, when I try to drag a horizontally draggable `PanelResizeHandle`, the cursor icon still indicates vertical dragging instead of switching to horizontal dragging.

### Steps to Reproduce:

1. Go to the [nested panels example](https://react-resizable-panels.vercel.app/examples/nested).
2. Drag a panel vertically.
3. Hover over a horizontally draggable PanelResizeHandle.

### Environment:
- Windows 11 Home
- Chrome 126.0.6478.185 (Official Build) (64-bit)

### Visual Evidence:
I have prepared a video demonstrating this issue. Please review it for a better understanding.

https://github.com/user-attachments/assets/0a5aff38-f94c-4c93-9728-feb6883a09be

Thank you for looking into this issue.

**Comment by bvaughn** [comment]
Hmm, this looks like maybe it could be related to pointer events in Chrome on Windows 11. (Like maybe there's an issue with the "pointerup" event or a ... no "pointermove" events afterward? Not sure.) Can't say I've seen this before, and I can't repro it on my end.

I'd be happy to review a PR if you have a change/proposal in mind.

**Comment by bvaughn** [comment]
Not sure I understand, @kaitoukid-1412. Seems like you're suggesting a change that would potentially undo the fix for #340 though?

**Comment by mohitsainiknl** [comment]
I'm facing the same problem. Any idea how to fix this?

**Comment by PabloCorso** [comment]
Would it possible to opt out the styling for the cursor? Aside from the current issue the styling seems like a sensible default, but in case of wanting to customise, the way styles are set makes it a bit hard to do it. 

Thanks for the great library!

**Comment by bvaughn** [comment]
> Would it possible to opt out the styling for the cursor? Aside from the current issue the styling seems like a sensible default, but in case of wanting to customise, the way styles are set makes it a bit hard to do it.

Published in version 2.1.0

---

❤️ → ☕ [givebrian.coffee](http://givebrian.coffee/)

**Comment by bvaughn** [comment]
Bugfix published in version 2.1.1

---

❤️ → ☕ [givebrian.coffee](http://givebrian.coffee/)
