### ISSUE TITLE
Add support for CSP nonce

### ISSUE THREAD

**Issue by asual** [bvaughn/react-resizable-panels#384]
Can you please consider adding support for a `nonce` attribute to the `style` element that this library injects in the DOM. The custom cursor logic currently doesn't work when CSP is configured to expect a specific nonce.

References:
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/nonce
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/style-src

**Comment by bvaughn** [comment]
Want to post a PR that adds a `nonce` prop and passes it through to the style in an effect?

**Comment by bvaughn** [comment]
> Can you please consider adding support for a `nonce` attribute to the `style` element that this library injects in the DOM. The custom cursor logic currently doesn't work when CSP is configured to expect a specific nonce.

Re-visiting this issue today and wanted to ask for clarification. This library does not inject a "`style` element" into the DOM. (No `N`.) It uses inline styles only.

**Comment by asual** [comment]
I didn't investigate much but I thought that the issue is caused by the [setGlobalCursorStyle](https://github.com/bvaughn/react-resizable-panels/blob/main/packages/react-resizable-panels/src/utils/cursor.ts#L80) function.

**Comment by bvaughn** [comment]
Ah, I believe you're right. It's been a while since I wrote that code and I had overlooked it because I was thinking about the panels/views themselves.

**Comment by asual** [comment]
The simplest fix for my specific case would be the addition of the following just before the linked [setGlobalCursorStyle](https://github.com/bvaughn/react-resizable-panels/blob/main/packages/react-resizable-panels/src/utils/cursor.ts#L80) line but it will be a very bundler-specific solution:
```styleElement.setAttribute("nonce", __webpack_nonce__);```

I guess we either need a new `PanelGroup` prop or some other workaround.

**Comment by bvaughn** [comment]
I can't add anything like that to this project :) Would need to think of a way for people to configure (opt in to) this functionality.

**Comment by bvaughn** [comment]
I didn't intend to close this issue when leaving my previous comment. (Sorry!)

**Comment by bvaughn** [comment]
Published in version 2.1.0

---

❤️ → ☕ [givebrian.coffee](http://givebrian.coffee/)
