### ISSUE TITLE
左侧面板的宽度不受浏览器尺寸变化影响

### ISSUE THREAD

**Issue by TestCabana** [bvaughn/react-resizable-panels#394]
如何实现浏览器的尺寸变化，不影响左侧面板的宽度，左侧面板的宽度只受拖动把手拖动来调整
How to change the size of the browser without affecting the width of the left panel, which is only adjusted by dragging the handle

**Comment by TestCabana** [comment]
![image](https://github.com/user-attachments/assets/16743a8f-7c1f-4b1d-86f2-05bbe730160f)
The width of the red box on the left panel is not affected by the browser's size page

**Comment by bvaughn** [comment]
Panels sizes are percentage based [as mentioned in the FAQs](https://github.com/bvaughn/react-resizable-panels?tab=readme-ov-file#can-panel-sizes-be-specified-in-pixels). If resizing the window resizes the panel group, then it will resize panels within the group. that is a limitation of this library.
