### ISSUE TITLE
Panel collapse mode

### ISSUE THREAD

**Issue by bvaughn** [bvaughn/react-resizable-panels#4]
Panels in VS Code can be fully _collapsed_ when shrunk past a certain point.

https://user-images.githubusercontent.com/29597/209335964-d77100b8-8a81-4c21-9b9c-2aa18474076e.mp4

This is an interesting UX that might be worth copying (if it can be done without adding a lot of complexity).

**Comment by bvaughn** [comment]
I think we might need to add a similar constraint as VS Code seems to– only the _first_ panel (or possibly the _last_) in a series can be collapsed like this.

**Comment by JeyRathnam** [comment]
Kinda unrelated to the issue, but the attached video files don't work on Firefox I guess, I get "No video with supported format and MIME type found".

**Comment by jyash97** [comment]
Maybe this is unrelated to this issue, but fixing the size of a specific panel could be a usecase I find appealing. We have a 3 layout panel, and the rightmost panel stays the same width. There's a way to make it work without any change. I find it be more useful if it was a prop based thing per `Panel`

**Comment by bvaughn** [comment]
@jyash97 I don't think it would make sense to add a _fixed size_ attribute exactly, because you could accomplish that already either by doing this:

```jsx
<PanelGroup direction="horizontal">
  <Panel>
    {/*...*/}
  </Panel>
  <ResizeHandle />
  <Panel>
    {/*...*/}
  </Panel>
  <ResizeHandle />
  <Panel defaultSize={30} minSize={30} maxSize={30}>
    {/*...*/}
  </Panel>
</PanelGroup>
```

Or this:
```jsx
<PanelGroup direction="horizontal">
  <Panel>
    {/*...*/}
  </Panel>
  <ResizeHandle />
  <Panel>
    {/*...*/}
  </Panel>

  <div className="fixed-size-panel">
    {/*...*/}
  </div>
</PanelGroup>
```

**Comment by jyash97** [comment]
Oh okay, just saw `maxSize` prop. Thanks for the clarification, I knew about the second option and first also makes sense.

Thanks

**Comment by bvaughn** [comment]
Note to self:
This library might be worth looking at how they accomplish their panel snap: https://github.com/orefalo/svelte-splitpanes

**Comment by bvaughn** [comment]
After some consideration, I think I'll go with a boolean attribute for this library– maybe `collapsible`. It can work _along with_ `minSize` to determine the point past which a panel collapses.

**Comment by bvaughn** [comment]
v0.0.27
