### ISSUE TITLE
Add maxSize to Panel

### ISSUE THREAD

**Issue by baumerdev** [bvaughn/react-resizable-panels#40]
Currently there is a property `minSize` that restricts flex-grow to become smaller than this value. Can you add a new property `maxSize` that restricts flex-grow to become larger than this value?

**Comment by bvaughn** [comment]
I imagine it could probably be done without a ton of effort.

**Comment by bvaughn** [comment]
@baumerdev I'd like to hear more about your use case.

**Comment by baumerdev** [comment]
Tried this lib with a three column layout in an app I'm currently working on. The first one is some kind of navigation which can contain custom entries of differing length (user input and/or i18n). So it is a nice feature to make this navigation a resizable Panel, but the entries won't exceed a certain length so it doesn't make sense for the user to expand the navigation Panel to the window's full width (or until minSize of the other Panels stop it) because most of the Panel will then be blank.

Just tried with Outlook which has some kind of maxSize mechanism that prevents the folder navigation to expand beyond a certain width. On the other hand macOS Mail doesn't stop you from resizing the folder navigation however stupid the window layout may look afterwards.

**Comment by bvaughn** [comment]
That makes sense. Thanks for elaborating.

I'll try to release `maxSize` in 0.0.23 probably sometime this afternoon.

**Comment by bvaughn** [comment]
Released in v0.0.23

**Comment by baumerdev** [comment]
Works like a charm. Thanks a lot.

**Comment by bvaughn** [comment]
Happy to hear it!
