### ISSUE TITLE
Controlled panel layout

### ISSUE THREAD

**Issue by nalaso** [bvaughn/react-resizable-panels#400]
Is there a way to control the left and right handlebar so that when the left handlebar is dragged to the right, the right handlebar also moves to the left?

https://github.com/user-attachments/assets/709ff28f-00c2-421e-ae4d-a9dc3d900536

**Comment by nalaso** [comment]
wondering if there is any layout change trigger so that i can use it inside useeffect dependency array

**Comment by bvaughn** [comment]
Yup! Check out either `onLayout` or `onResize` in the docs: https://github.com/bvaughn/react-resizable-panels/tree/main/packages/react-resizable-panels. I think they might work for you.

**Comment by nalaso** [comment]
Yeah it worked!!


https://github.com/user-attachments/assets/daf55ce0-d906-4e60-bcde-493f65097ed3

**Comment by nalaso** [comment]
implemented using onLayout and setLayout

**Comment by bvaughn** [comment]
Nice! Glad you figured out a solution :)
