### ISSUE TITLE
How to hide panel + handle onCollapse

### ISSUE THREAD

**Issue by ikulity** [bvaughn/react-resizable-panels#402]
How can I hide/close both the panel + handle onCollapse without any side effects?

### How to reproduce

- Open sandbox: https://codesandbox.io/p/sandbox/react-resizable-panels-forked-v5xgnj?workspaceId=5a30d24e-0530-4f5f-89d0-bc166539705a
- Drag the first handle up until the first panel is closed
- Open the first panel by clicking "Show top panel"
- Hover over the first handle
  - handle is still being dragged by the mouse
  - Also any items in this first panel cannot be clicked

### Expected behavior

After collapsing by drag and then showing the panel again the panel should behave normally and mouse shouldn't be connected to the handle

Only sandbox modifications are the onCollapse + minSize props I gave to the Panels

**Comment by bvaughn** [comment]
This looks like a bug in the drag/resize code. I'll take a look.

**Comment by bvaughn** [comment]
Fixed in 2.1.3

---

❤️ → ☕ [givebrian.coffee](http://givebrian.coffee/)
