### ISSUE TITLE
Working with table elements

### ISSUE THREAD

**Issue by BrendonChirume** [bvaughn/react-resizable-panels#411]
Suppose you change the display property of the `ResizablePrimitive.PanelGroup`  to anything other than flex, the resizing stops working altogether.

**Comment by bvaughn** [comment]
That's not supported. This library uses flexbox layout to work.

**Comment by bvaughn** [comment]
I should add that <table> elements require a specific type of nested DOM structure that (I don't think) would really make sense to use with a library like this. If you want to use this library to resize a table though, perhaps you could render a horizontal panel group and then listen to its `onResize` event and mirror the sizes in your table columns?
