### ISSUE TITLE
preline.js:152 Uncaught TypeError: Cannot read properties of undefined (reading 'getAttribute')

### ISSUE THREAD

**Issue by lgf5090** [bvaughn/react-resizable-panels#416]
![image](https://github.com/user-attachments/assets/0d2245fb-3b38-401a-8353-0c9453eb58c6)

**Comment by bvaughn** [comment]
I can't help with this. I have no idea what the code in your screenshot is or how to repro the issue. If you share something I can reproduce and debug (either a GitHub project I can check out and run or a Code Sandbox) I'll take a look.
