### ISSUE TITLE
Does this work with React Native?

### ISSUE THREAD

**Issue by ofersadgat** [bvaughn/react-resizable-panels#421]
There doesnt seem to be any documentation around this. I tried to look at the code and theres a bit:
```
tagName: Type = "div",
```
which make it seem like you could pass in `View` instead? Thanks for the work!

**Comment by bvaughn** [comment]
No. This supports react-dom only.

**Comment by ofersadgat** [comment]
Out of curiosity, do you know if it would be difficult to add support? (not asking you to, just curious if it might be worthwhile to try myself) What assumptions are made which this would break?
