### ISSUE TITLE
Unable to get panel size on first render.

### ISSUE THREAD

**Issue by yf-yang** [bvaughn/react-resizable-panels#440]
Say I want to render an icon, the icon is based on panel size, so I need to get its size when its first rendered.

Since there is no such API, I trie the following:
``` ts
function Component() {
  const ref = useRef<ImperativePanelHandle>(null);
  const [_open, setOpen] = useState<boolean | undefined>(undefined);
  useEffect(() => {
    if (_open === undefined) {
      setOpen(!ref.current!.isCollapsed());
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps -- the effect should only run once
  }, []);
  return (<Panel ref={ref} />);
}
```

However, it turns out to be the panel size is not available when the first effect runs, and fails to pass the assertion.

How to achieve the functionality here?

**Comment by bvaughn** [comment]
> and fails to pass the assertion.

I don't know what assertion you're referring to. The code above has no assertion.

> it turns out to be the panel size is not available when the first effect runs
> How to achieve the functionality here?

I would suggest checking out the docs:
https://github.com/bvaughn/react-resizable-panels/tree/main/packages/react-resizable-panels#panel

Specifically, there's an `onResize` method I would suggest using for this. It will be called on mount with the initial size.

**Comment by yf-yang** [comment]
@bvaughn Thank you, I'll give it a try.

FYI, the assertion is here:
https://github.com/bvaughn/react-resizable-panels/blob/fa58630e0ba09070f6977ce0ab036588a8749ce4/packages/react-resizable-panels/src/PanelGroup.ts#L348-L351
