### ISSUE TITLE
Add minSize/maxSize, but in pixels

### ISSUE THREAD

**Issue by NepeinAV** [bvaughn/react-resizable-panels#46]
Hi! Can you add min/max panel size restrictions, but in pixels? Sometimes, if the window size becomes too small, panel content may shrink too much, which causes UI issues (overflows, etc.).

**Comment by bvaughn** [comment]
I understand why that would be convenient in some cases but I don’t think it’s  something I want to support- because it would require changing the public api in a non obvious way (since this library doesn’t control its own outer dimensions).

You should be able to accomplish this using minSize and a minimum external height/width though!

**Comment by bvaughn** [comment]
Copying from https://github.com/bvaughn/react-resizable-panels/issues/48#issuecomment-1368106118 in case others see this issue.

---

Here is an example of what I mean:
https://codesandbox.io/s/react-resizable-panels-forked-m5qf69?file=/src/App.js

```js
  const MIN_SIZE_IN_PIXELS = 100;

  const [minSize, setMinSize] = useState(10);

  useLayoutEffect(() => {
    const panelGroup = document.querySelector('[data-panel-group-id="group"]');
    const resizeHandles = document.querySelectorAll(
      "[data-panel-resize-handle-id]"
    );
    const observer = new ResizeObserver(() => {
      let height = panelGroup.offsetHeight;

      resizeHandles.forEach((resizeHandle) => {
        height -= resizeHandle.offsetHeight;
      });

      // Minimum size in pixels is a percentage of the PanelGroup's height,
      // less the (fixed) height of the resize handles.
      setMinSize((MIN_SIZE_IN_PIXELS / height) * 100);
    });
    observer.observe(panelGroup);
    resizeHandles.forEach((resizeHandle) => {
      observer.observe(resizeHandle);
    });

    return () => {
      observer.disconnect();
    };
  }, []);
```

**Comment by bvaughn** [comment]
I think I have a possible solution for the pixel-based constraints; see https://github.com/bvaughn/react-resizable-panels/pull/176

---

❤️ → ☕ [givebrian.coffee](http://givebrian.coffee/)

**Comment by sleeyax** [comment]
If anyone is looking for a recent example to simply get the height of a panel to React state, you can use this hook I came up with (which is based on the original answer):

```ts
// usePanelHeight.ts

import { useLayoutEffect, useState } from "react";
import { getPanelElement } from "react-resizable-panels";

/**
 * Custom hook to get the height of a panel from `react-resizable-panels`.
 * @param id The id of the panel to get the height of.
 */
export function usePanelHeight(id: string) {
  const [height, setHeight] = useState<number>();

  useLayoutEffect(() => {
    const panelElement = getPanelElement(id);

    if (panelElement) {
      const observer = new ResizeObserver(() =>
        setHeight(panelElement.offsetHeight),
      );

      observer.observe(panelElement);

      return () => observer.disconnect();
    }
  }, []);

  return height;
}
```

Usage:

```tsx
export function MyPanelsComponent() {
  const height = usePanelHeight("my-panel-id"); // the same id must be specified in the ResizablePanel below.

  return (
    <ResizablePanelGroup direction="vertical">
      <ResizablePanel id="my-panel-id">
        <MyComponent panelHeight={height} />
      </ResizablePanel>
      <ResizableHandle />
      <ResizablePanel>
        <SomeOtherComponent />
      </ResizablePanel>
    </ResizablePanelGroup>
  );
}
```

**Comment by Albinzr** [comment]
This will solve your issue
   <ResizablePanel
              minSize={2}
              defaultSize={2}
              style={{
                "min-width": "40  px",
                "max-width": "400  px",
              }}
            >

**Comment by Albinzr** [comment]
@NepeinAV I think this can help you guys 
a simple css

 <ResizablePanel
              minSize={2}
              defaultSize={2}
              style={{
                "min-width": "40px",
                "max-height":"400px"
              }}
            >

**Comment by johnstack01** [comment]
> If anyone is looking for a recent example to simply get the height of a panel to React state, you can use this hook I came up with (which is based on the original answer):
> 
> ```ts
> // usePanelHeight.ts
> 
> import { useLayoutEffect, useState } from "react";
> import { getPanelElement } from "react-resizable-panels";
> 
> /**
>  * Custom hook to get the height of a panel from `react-resizable-panels`.
>  * @param id The id of the panel to get the height of.
>  */
> export function usePanelHeight(id: string) {
>   const [height, setHeight] = useState<number>();
> 
>   useLayoutEffect(() => {
>     const panelElement = getPanelElement(id);
> 
>     if (panelElement) {
>       const observer = new ResizeObserver(() =>
>         setHeight(panelElement.offsetHeight),
>       );
> 
>       observer.observe(panelElement);
> 
>       return () => observer.disconnect();
>     }
>   }, []);
> 
>   return height;
> }
> ```
> 
> Usage:
> 
> ```tsx
> export function MyPanelsComponent() {
>   const height = usePanelHeight("my-panel-id"); // the same id must be specified in the ResizablePanel below.
> 
>   return (
>     <ResizablePanelGroup direction="vertical">
>       <ResizablePanel id="my-panel-id">
>         <MyComponent panelHeight={height} />
>       </ResizablePanel>
>       <ResizableHandle />
>       <ResizablePanel>
>         <SomeOtherComponent />
>       </ResizablePanel>
>     </ResizablePanelGroup>
>   );
> }
> ```

How do you set the minSize/maxSize using this pattern?

**Comment by NepeinAV** [comment]
> @NepeinAV I think this can help you guys 
> 
> a simple css
> 
> 
> 
>  <ResizablePanel
> 
>               minSize={2}
> 
>               defaultSize={2}
> 
>               style={{
> 
>                 "min-width": "40px",
> 
>                 "max-height":"400px"
> 
>               }}
> 
>             >

I ended up using "allotment", which works pretty well for me. For example, https://sql-academy.org/trainer/tasks/1

**Comment by johnstack01** [comment]
It doesn't have the collapsible panel feature tho. Otherwise seems nice.

**Comment by RomneyDa** [comment]
I don't think this has been brought up, if you have the [container](https://stackoverflow.com/questions/69819938/is-there-any-other-easy-way-to-get-the-height-and-width-of-a-container-using-rea)  or [screen](https://medium.com/@josephat94/building-a-simple-react-hook-to-detect-screen-size-404a867fa2d2) dimensions, you can also just reverse calculate the percentage. 

e.g.,

```ts
export function MyPanels() {
    const { width } = useContainerDimensions(); // or useScreenSize(), etc.
    const minSizePixels = 200;
    const minSizePercentage = minSizePixels / width * 100;
    return (
      <ResizablePanelGroup direction="horizontal">
        <ResizablePanel minSize={minSizePercentage}>Stuff 1</ResizablePanel>
        <ResizableHandle />
        <ResizablePanel>Stuff 2 </ResizablePanel>
      </ResizablePanelGroup>
    );
}
```

**Comment by yzhou-willow** [comment]
> Copying from [#48 (comment)](https://github.com/bvaughn/react-resizable-panels/issues/48#issuecomment-1368106118) in case others see this issue.
> 
> Here is an example of what I mean: https://codesandbox.io/s/react-resizable-panels-forked-m5qf69?file=/src/App.js
> 
>   const MIN_SIZE_IN_PIXELS = 100;
> 
>   const [minSize, setMinSize] = useState(10);
> 
>   useLayoutEffect(() => {
>     const panelGroup = document.querySelector('[data-panel-group-id="group"]');
>     const resizeHandles = document.querySelectorAll(
>       "[data-panel-resize-handle-id]"
>     );
>     const observer = new ResizeObserver(() => {
>       let height = panelGroup.offsetHeight;
> 
>       resizeHandles.forEach((resizeHandle) => {
>         height -= resizeHandle.offsetHeight;
>       });
> 
>       // Minimum size in pixels is a percentage of the PanelGroup's height,
>       // less the (fixed) height of the resize handles.
>       setMinSize((MIN_SIZE_IN_PIXELS / height) * 100);
>     });
>     observer.observe(panelGroup);
>     resizeHandles.forEach((resizeHandle) => {
>       observer.observe(resizeHandle);
>     });
> 
>     return () => {
>       observer.disconnect();
>     };
>   }, []);

This won't work for current version ^2.0.0 when the container size changes. Steps:
1. Resize the panel and it will store the size in local storage 
```
'1:{"minSize":14},2:{},2:{}' : {
    "expandToSizes": {},
    "layout": [
        15.23454838,
        51.4321182867,
        33.3333333333
      ]
}
```
2. Resizes the window (it's window heigh in this example)
3. Resize the panel again, and a key value pair will be added:
```
'1:{"minSize":21},2:{},2:{}' : {
    "expandToSizes": {},
    "layout": [
        33.3333333334,
        33.3333333333,
        33.3333333333
    ]
}
``` 
4. Then reload the page and the layout size will be reset to:
```
[
  33.3333333334,
  33.3333333333,
  33.3333333333
]
```

https://codesandbox.io/p/devbox/react-resizable-panels-forked-3n28lq?workspaceId=ws_2MmMkzQan9CUm77TJGU6Za

**Comment by bvaughn** [comment]
Adding this comment to a few older issues, but I am currently considering an idea (see https://github.com/bvaughn/react-resizable-panels/issues/496#issuecomment-3099991742) that might be useful in supporting pixel-based constraints. Just an FYI in case you have any thoughts about that direction.

(I know this is an old issue, so feel free to ignore this comment if you are no longer interested in this feature.)

**Comment by softmarshmallow** [comment]
This can't be real. at this point, the library should implement dedicated (duplicate) version of the panel, just for Px.

`import * from "react-resizable-panels/px"`

**Comment by bvaughn** [comment]
Can’t be real? Please. No one’s stopping you from building that in your own library, @softmarshmallow. Last time I checked, I was doing all of this stuff for free.

**Comment by softmarshmallow** [comment]
> Can’t be real? Please. No one’s stopping you from building that in your own library, [@softmarshmallow](https://github.com/softmarshmallow). Last time I checked, I was doing all of this stuff for free.

Woah. no offense at all!
