### ISSUE TITLE
Hope to support more property settings

### ISSUE THREAD

**Issue by qqdb** [bvaughn/react-resizable-panels#51]
This is a great job, but when setting defaultSize, maxSize, minSize and other attributes, only numbers are supported. In use, pixels need to be used to operate elements more precisely, and more setting methods are expected to be supported.

**Comment by bvaughn** [comment]
See this comment for an example of how to set pixel sizes: https://github.com/bvaughn/react-resizable-panels/issues/47#issuecomment-1368108429

and also for rationale of why I don’t plan to add support for that to the library directly 🙇🏼

**Comment by bvaughn** [comment]
Copying from https://github.com/bvaughn/react-resizable-panels/issues/48#issuecomment-1368106118 in case others see this issue and would find this a helpful direction to expore:

---

Here is an example of what I mean:
https://codesandbox.io/s/react-resizable-panels-forked-m5qf69?file=/src/App.js

```js
  const MIN_SIZE_IN_PIXELS = 100;

  const [minSize, setMinSize] = useState(10);

  useLayoutEffect(() => {
    const panelGroup = document.querySelector('[data-panel-group-id="group"]');
    const resizeHandles = document.querySelectorAll(
      "[data-panel-resize-handle-id]"
    );
    const observer = new ResizeObserver(() => {
      let height = panelGroup.offsetHeight;

      resizeHandles.forEach((resizeHandle) => {
        height -= resizeHandle.offsetHeight;
      });

      // Minimum size in pixels is a percentage of the PanelGroup's height,
      // less the (fixed) height of the resize handles.
      setMinSize((MIN_SIZE_IN_PIXELS / height) * 100);
    });
    observer.observe(panelGroup);
    resizeHandles.forEach((resizeHandle) => {
      observer.observe(resizeHandle);
    });

    return () => {
      observer.disconnect();
    };
  }, []);
```

**Comment by bvaughn** [comment]
Check out https://github.com/bvaughn/react-resizable-panels/pull/176
