### ISSUE TITLE
Collapse on click

### ISSUE THREAD

**Issue by josh-unwin** [bvaughn/react-resizable-panels#55]
Thanks for the really nice package!

One feature I'd love to see is the ability to close and open (ie; collapse) a panel on click of the ResizeHandle.

**Comment by bvaughn** [comment]
I don't think that's a feature I want to add to this library. Clicking on a resize handle is part of the normal drag-to-resize, so overloading it to also collapse seems to me like it would be a confusing UX.

If I understand you correctly though, you can implement this functionality yourself in application code doing something like this:
https://codesandbox.io/s/react-resizable-panels-forked-fek6pp

**Comment by jyash97** [comment]
Hey @bvaughn  👋 

Sorry to hack the thread, but saw a issue in above codesandbox

1. Collapse panel by clicking handle
2. Click handle again 
3. resize using the bottom handle (first panel gets resize)

Not sure if this was a expected issue, if so you can ignore this 

**Video:**

https://user-images.githubusercontent.com/22376783/210371516-b45d818d-5c23-4259-9423-86e320a1653d.mov

**Comment by bvaughn** [comment]
Ah, right. That's interesting.

**Comment by bvaughn** [comment]
Fixed!

https://codesandbox.io/s/react-resizable-panels-forked-fek6pp

**Comment by josh-unwin** [comment]
Hi @bvaughn, thanks for the quick reply!

That's completely understandable, I've been battling with making such a feature work elegantly so I think I'll just ditch the idea.

Just to show you the sort of UX I imagined (it was based on another tool that implemented a similar feature but for the life of me I can't find it now!):

https://user-images.githubusercontent.com/49525488/210399696-a8ec5d69-7ee2-4c3c-8dc2-c7d52e024272.mp4

The handle is quite thick and closed by default, clicking on it opens it up to a default size but can also be resized, clicking again collapses it. The arrow would change direction based on whether it's collapsed or open.

**Comment by bvaughn** [comment]
@josh-unwin I see!

I think you can build _almost_ the same thing now _except_ for the click-to-collapse.
