### ISSUE TITLE
Collapse/open via external component

### ISSUE THREAD

**Issue by josh-unwin** [bvaughn/react-resizable-panels#56]
A use-case I would have for this would be clicking on a list item to open up a detailed side panel view, it would great if the library could include the functionality of triggering the opening of the side panel on click of another element.

**Comment by bvaughn** [comment]
Hey Josh.

I'm trying to keep this library small and focused on resizable layouts only. That's my primary use case and that's all I have time to support.

What you're describing sounds kind of specific to a certain type of application. I don't think it relates to resizing panels. I think you can build it on top of this library though. Your list of items could be rendered inside of a `Panel` (or multiple `Panel`s) and you could show the detail view as a [conditional `Panel`](https://react-resizable-panels.vercel.app/examples/conditional) when clicked.

**Comment by josh-unwin** [comment]
Thanks again @bvaughn

That's understandable, I would argue that it's quite likely to be a common application.
If clicking on an element in one panel displays content in another panel, but the user has collapsed the second panel, then it will appear as if nothing has happened to the user. Especially as the library stores panel state, if they collapsed it on last use they'll probably have forgotten that next time.

I guess it's comparable to the buttons on the far-left of VSCode, if the sidebar is collapsed, clicking on one opens it up again.

That's why the conditional display suggestion doesn't work, it doesn't solve the situation where the panel is shown but collapsed.

I guess the implementation would be making an extra import, something like:

```
import { Panel, setPanelSize } from 'react-resizable-panels';

setPanelSize('panel-id', size) 
```

Just my 2 cents!

**Comment by bvaughn** [comment]
@josh-unwin Seems like your use case is similar to the one being discussed on #58.
