### ISSUE TITLE
Render custom PanelResizeHandle based on whether it's resizing or not

### ISSUE THREAD

**Issue by skyrpex** [bvaughn/react-resizable-panels#59]
## What you did:

I'm using a styled resize handle, like the following:

```tsx
<panels.PanelResizeHandle className="w-0.5 relative">
    <div className="absolute inset-y-0 -left-[0.1875rem] w-1.5 bg-blue-500 opacity-0 hover:opacity-100 transition-opacity"></div>
</panels.PanelResizeHandle>
```

It basically becomes blue on hover.

![image](https://user-images.githubusercontent.com/1077520/210412575-fee90941-891b-4e97-a739-6202f6e7fda2.png)

## What happened:

The problem is that, while resizing, the handle will stop being highlighted in blue if the mouse moves too fast. It happens because the mouse won't be on top of the handle for a few milliseconds. 

## Suggested solution:

The `PanelResizeHandle` component could pass a `isResizing` boolean to its children so we can keep the highlighting in place. It'd look like this:

```tsx
<panels.PanelResizeHandle className="w-0.5 relative">
    {({ isResizing }) => (
        <div className={classNames("absolute inset-y-0 -left-[0.1875rem] w-1.5 bg-blue-500 hover:opacity-100 transition-opacity", { "opacity-100": isResizing, "opacity-0": !isResizing })}></div>
    )}
</panels.PanelResizeHandle>
```

**Comment by bvaughn** [comment]
The `PanelResizeHandle` component sets a data attribute for custom styling:
* `data-resize-handle-active: "pointer" | "keyboard" | undefined`

I think you should be able to set a style like you're describing using a CSS selector like this:
```css
.ResizeHandle[data-resize-handle-active="pointer"] {
  /* ... */
}
```

**Comment by shshaw** [comment]
Just noting that `setPointerCapture` [as mentioned here](https://github.com/bvaughn/react-resizable-panels/pull/50#issuecomment-1370034470) would help keep hover styles active regardless of if the cursor has moved off.

https://codepen.io/shshaw/pen/zYLKGje

**Comment by bvaughn** [comment]
Quick follow up to this now that [0.0.37](https://github.com/bvaughn/react-resizable-panels/blob/main/packages/react-resizable-panels/CHANGELOG.md#0037) has been released.

In addition to the `data-resize-handle-active` attribute based style, you can also use the new `onDragging` callback. For example:
https://codesandbox.io/s/react-resizable-panels-forked-di6vn0?file=/src/styles.module.css
