### ISSUE TITLE
Compile Error with Create React App with React 17

### ISSUE THREAD

**Issue by tioluwani94** [bvaughn/react-resizable-panels#67]
Hello 👋🏽,

I'm getting a compile error when I try to use the `react-resizable-panels` components in my project:

<img width="666" alt="Screenshot 2023-01-05 at 5 26 57 PM" src="https://user-images.githubusercontent.com/11310046/210830517-12bef2ac-cecb-436b-b36e-d10a563f671f.png">

I have the following setup in my `package.json`:

`
"react": "17.0.0",
"react-dom": "17.0.0",
"react-scripts": "4.0.3",
`

I'll appreciate any pointers to resolve this, thank you!

**Comment by bvaughn** [comment]
The operator causing the error you're reporting is the [nullish coalescing operator (`??`)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing):
```js
return state[key] ?? null;
```

Guessing create-react-app isn't configured to handle that. I don't know what the best fix is.

**Comment by tioluwani94** [comment]
Hi, @bvaughn thanks for the response it was very helpful. I was able to resolve the issue with the help of this:
https://github.com/facebook/create-react-app/issues/9468.

**Comment by bvaughn** [comment]
Glad to hear it!

**Comment by bvaughn** [comment]
FYI, I removed the nullish coalescing operator in v0.0.31 because the trivial benefit it provided didn't seem worth causing headaches for create-react-app users.

**Comment by tioluwani94** [comment]
Alright, thanks for the update.

**Comment by bvaughn** [comment]
By the way, if you update to 0.0.35– this module should now work with CRA without any additional configuration changes.
https://github.com/bvaughn/react-resizable-panels/releases/tag/v0.0.35

**Comment by tioluwani94** [comment]
> By the way, if you update to 0.0.35– this module should now work with CRA without any additional configuration changes.
> 
> https://github.com/bvaughn/react-resizable-panels/releases/tag/v0.0.35

Thanks for the update @bvaughn

**Comment by daeniel** [comment]
By the way, if you update to 0.0.35– this module should now work with CRA without any additional configuration changes.

https://github.com/bvaughn/react-resizable-panels/releases/tag/v0.0.35

Thanks for the update @bvaughn

**Comment by daeniel** [comment]
By the way, if you update to 0.0.35– this module should now work with CRA without any additional configuration changes.

https://github.com/bvaughn/react-resizable-panels/releases/tag/v0.0.35

Thanks for the update @bvaughn
