### ISSUE TITLE
New size should only be committed after dragging ends

### ISSUE THREAD

**Issue by Janpot** [bvaughn/react-resizable-panels#70]
Currently, when dragging panel 'right' and causing another panel 'left' to resize, it immediately commits the new size of the panel 'left', even if I drag panel 'right' back to its original position. See:

https://user-images.githubusercontent.com/2109932/211297716-3fa17db4-f9f3-466c-b1c3-5f82bf875e19.mov

It feels counterintuitive, since it's quite common that I'm not 100% precise on my drag and will overshoot. Ideally all new sizes are only committed after I release the mouse button and panels spring back to their original position. See e.g. in vscode:

https://user-images.githubusercontent.com/2109932/211298099-6b904fad-f143-4e0b-985e-b0ce49015c16.mov

**Comment by bvaughn** [comment]
I have a TODO in the code somewhere to look into how difficult it would be to implement this behavior. I _thought_ I had a GitHub issue too but it seems I didn't. 😄  I agree this would be a nice change! Don't know when I'll get around to it though.

**Comment by bvaughn** [comment]
On a flight today so I have some time to play with this. The idea I've been chewing over in the back of my head is to capture the initial panel sizes when dragging begins– and apply the drag delta _to them_ (rather than to the _current_ sizes). I think this would work out and require very little code.

**Comment by bvaughn** [comment]
This will go out with the next release, 0.0.34

**Comment by Janpot** [comment]
👍 Works well, great work!

**Comment by bvaughn** [comment]
Just published as v0.0.34

Full release notes here:
https://github.com/bvaughn/react-resizable-panels/blob/main/packages/react-resizable-panels/CHANGELOG.md#0034
