### ISSUE TITLE
Cursor not changing back to default cursor after using keyboard to control panel resize handle

### ISSUE THREAD

**Issue by cristianpjensen** [bvaughn/react-resizable-panels#86]
The cursor does not change back to the default cursor after using the keyboard to reposition the resize handle. It only changes back after having used the cursor to reposition the resize handle. Until then, it stays on `col-resize` and only changes back to `default` after using the cursor.

Video of this happening:
![2023-01-17 16 56 50](https://user-images.githubusercontent.com/62624115/212947310-3ec4f7c0-7e63-4278-a4da-e7cadaf938da.gif)

**Comment by bvaughn** [comment]
Will will be included in v0.0.34

**Comment by cristianpjensen** [comment]
Great!

**Comment by bvaughn** [comment]
Just published as v0.0.34

Full release notes here:
https://github.com/bvaughn/react-resizable-panels/blob/main/packages/react-resizable-panels/CHANGELOG.md#0034
