### ISSUE TITLE
Support (or recommended approach) for handling "position: absolute" panels

### ISSUE THREAD

**Issue by viveleroi** [bvaughn/react-resizable-panels#93]
We have a sidebar navigation panel on the left, and main content on the right, and a resizer between them.

I'm sure this is a fairly niche requirement but the navigation panel can be "unpinned" meaning it's given `position: absolute` and is "disconnected" from the main content so that the main content expands/"falls behind" the sidebar, yet the sidebar can continue to be expanded and collapsed as if the main content was still there.

Because this is using flex, it's not automatically compatible with an absolute panel. I was wondering if you can recommend a solution?

My initial thoughts are to use `onResize` to set fixed dimensions if it's supposed to be unpinned.

P.S. Sorry for filing an issue, I didn't see a better place to ask

**Comment by bvaughn** [comment]
Hey Mike.

The scenario you're describing seems pretty niche, like you said. I don't think it's something I'd want to add much code to this component to facilitate.

That being said– I think you _could_ accomplish by attaching a [`ResizeObserver`](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver) to your "detachable" panel content. Let react-resizable-panels control the component size until/unless it gets "disconnected", then use the most recent that you recorded with the `ResizeObserver` as the "floating" size.

(I don't think `onResize` would be sufficient, since this is only triggered when the panel's relative size changes within the group, and you would also want to react to changes to the outer group/window size.)

Hopefully this is enough to unblock you (so I'm going to close the issue). Let me know if you hit a snag though. Share a Code Sandbox and I'll take a look.

**Comment by viveleroi** [comment]
Thanks for the input, I'll toy around and see what I can get. Just to be clear, I need the panel to always be resizable, so I can't simply set the size when "unpinned" etc. I'll have to find a way for the resize to continue.

I honestly wish we could abandon this requirement entirely, it's so annoying to account for.

**Comment by bvaughn** [comment]
Oh, I see. That’s a bit more complicated then. Hmm. It’s possible this library isn’t a great solution for you at this point then, BUT…

You could try:
1. Use onResize to track the current relative size
2. When detached, render a second group but with the other panel empty (nothing in the Panel) so the visible floating panel was still resizable.

**Comment by viveleroi** [comment]
Thanks, I was debating a second empty panel so I guess it's a little better that you agree it's a possible hacky solution.

> this library isn’t a great solution

I've been looking at all of the alternatives for two reasons - this issue and the fact we need min/max/default sizes in pixels. You've posted a workaround for pixel part which I've gotten working in my test of this lib (extracted it into a hook for reusability, we'll need it in many places). But, probably no surprise, no one supports this use case. Out of all of the other libs, this one looks to be better developed. The rest seem incomplete, buggy, long out of date, etc.

If you know of any that might work better for me needs let me know but I doubt it.

**Comment by bvaughn** [comment]
If I come across one, I'll let you know. I built this one because I didn't see any that I liked though 😄

**Comment by viveleroi** [comment]
Too much of my development life is doing just that, so I'm eager to not write a custom solution just for one niche feature.

**Comment by viveleroi** [comment]
Outside of this issue I've gotten the library integrated into our app and am happy with it. I ditched the fixed-pixel sizes too and will push our design team to accept percentages.

One thing I wish I had a was a classname on the resize handle based on the direction of the panel group. I can easily add a classname myself but am trying to reduce what other devs in our app have to remember to add. For now I'm using `.resize-handle[data-panel-group-direction='horizontal']`

Anyway, now I get to solve this absolute positioning issue. I see no way to do this beyond what you suggested, and invisible panel on the other side.

**Comment by bvaughn** [comment]
My suggestion would be to export your own rapper component that attaches a default className prop (and then just use that rather than importing to resize handle directly). That’s what I do for the apps that I use this library in.

It’s a little verbose but if you don't want to pass your own prop, you could also use:
[data-panel-resize-handle-id][data-panel-group-direction='horizontal']

I don't think I’ll add a static default className to the DOM element.

**Comment by viveleroi** [comment]
Just to be sure I understand your suggestion, when our "navigation drawer" is supposed to be "unpinned" aka floating and resizable above the other panels, you suggested rendering a second panel group.

If I understand you right, that appear to work at first glance but:

- After "pinning" the nav drawer the second resizer panel group logics breaks. Resizers move in the wrong directions, and appear to be moving wrong content. When I render each panel group by them selves, they work as intended so I know it's not anything wrong in the setup. I think the library just didn't expecting new panels.
- I'm worried that rendering two different versions of `NavigationDrawer` component like this is a bad practice.
- This is a lot more verbose than I'd like (this will have to replicated in dozens of modules) but it's still better than writing a custom resizer lib... which I may need to do anyway.

```js
{!isPinned && (
  <ResizePanelGroup className={clsx('pinnable', { pinned: isPinned })} direction='horizontal' id='submodule'>
    <ResizePanel className='flex' minSize={20}>
      <NavigationDrawer isPinned={isPinned} setIsPinned={setIsPinned}><div>tree</div></NavigationDrawer>
    </ResizePanel>
    <ResizeHandle />
    <ResizePanel defaultSize={30} minSize={10}>
      <div>invisible area</div>
    </ResizePanel>
  </ResizePanelGroup>
)}
<ResizePanelGroup direction='horizontal' id='grid'>
  {isPinned && (
    <ResizePanel className='flex' defaultSize={15} minSize={10}>
      <NavigationDrawer isPinned={isPinned} setIsPinned={setIsPinned}><div>tree</div></NavigationDrawer>
    </ResizePanel>
  )}
  <ResizeHandle />
  <ResizePanel className='flex'>
    <SubmoduleContent>
      content goes here
    </SubmoduleContent>
  </ResizePanel>
  <ResizeHandle />
  <ResizePanel className='flex' defaultSize={15} minSize={10}>
    <div>quick edit drawer</div>
  </ResizePanel>
</ResizePanelGroup>
```

**Comment by bvaughn** [comment]
I don't think I can do more than give general guidance, though if you'd put together a Code Sandbox demo I will take a look and see if I spot something.

**Comment by viveleroi** [comment]
I understand and I appreciate your insight, this is just something that all resizer libs weren't designed to handle. Our old application had this functionality only because I personally built a custom resizer lib a decade ago for AngularJS and it was not something I want to do again.

Here's a demo:

https://codesandbox.io/s/react-resizable-panels-forked-ot688i?file=/src/root.css

You'll see several resize panels. The navigation and quick-edit areas are "drawers" that sit against the left and right of the screen, with their inner border resizable horizontal. The main grid and details panels sit in the middle, with their border resizable vertically.

By default, the navigation (and quick-edit realistically, but I've left that out for this demo) are "pinned". That means they're position: relative/auto and they fully influence the main grid/details areas like any typical resizer demo.

When "unpinned" by clicking a button they become `position: absolute` - they get "disconnected" from the other elements - the main grid/details are is no longer influenced by anything the nav does. They "fall behind" the drawers and the drawers are free to be resized "over" that content as it's now free-floating.

On first load of the demo, everything works fine because they're all one panel group. When "unpinning" the nav for the first time, it still works fine because it's a new panel group covering the old one.

However, once "pinned" again, everything goes haywire. Resizers go in the wrong direction etc.

Maybe I can do a better job of conditionally rendering panels and groups? One of my concerns is that I don't like having two "versions" of `Drawer` in the dom, that seems like code smell. 

I appreciate your time.

**Comment by bvaughn** [comment]
Try:
1. Adding `order` props to each of the `Panel` components.
2. Adding `autoSaveId` to each of the `PanelGroup` components.

https://codesandbox.io/s/react-resizable-panels-forked-ebb174

---

I think you could possibly _also_ get away with just rendering one `PanelGroup` and conditionally rendering part of it as a `Panel` or not, but I don't understand your application well enough to really pitch that.

**Comment by bvaughn** [comment]
Good luck! 😄

**Comment by viveleroi** [comment]
I have z-indexes set so the background content is accessible now, do you have any idea why, when the nav is "unpinned" the quick-edit handle doesn't move? It should just be a normal 2 panel group with a resize handle between them. I even tried setting the order. It just doesn't respond to clicks at all, no console errors.

https://codesandbox.io/s/react-resizable-panels-forked-0exlqp?file=/src/App.js

**Comment by viveleroi** [comment]
Made a comment but just deleted it, moved some of the panel code around and it works.

This is incredibly "hacky" but it *appears* to be doing what I want. Thanks for your help.

**Comment by bvaughn** [comment]
Glad to hear! 😁
