### ISSUE TITLE
Scrollbars appear on drag event

### ISSUE THREAD

**Issue by nicolasthy** [bvaughn/react-resizable-panels#96]
Hey 👋 Congrats on the lib, it's amazing!
I just have a small issue when working with nested panels. If I start resizing a panel in the parent `PanelGroup`, all scrollbars contained in the child `PanelGroup` will appear. Any idea what's going on and how I could fix this?

https://user-images.githubusercontent.com/4039090/215148115-8276878c-887f-4636-8d81-7226e29db77a.mov

If needed I can try to replicate on CodeSandbox, let me know

**Comment by nicolasthy** [comment]
So I tried to use Replay.io but unfortunately there's no issue on their browser 🤔 
Here's a quick repro in Code Sandbox where I still have the issue using Chrome: https://codesandbox.io/s/romantic-einstein-uz4xuw?file=/src/App.js

**Comment by bvaughn** [comment]
Interesting. If you MacOS configured to show scrollbars "_based on mouse or trackpad_" then you don't even need to resize to see the scrollbars. Just mousing down on the scrollbar (and not moving) is enough to show them in Chrome. Also, you _can_ resize (via keyboard) without any scrollbars being shown:

https://user-images.githubusercontent.com/29597/215780548-d04e03d0-1245-4c15-8c99-affc87f5eeda.mp4

Performance profiling in Chrome doesn't really show anything happening. I'm not sure what's going on. I wouldn't think this is event related to `react-resizable-panels`– except that I tried reproducing with just HTML+CSS ([nk7iei](https://nk7iei.csb.app/)) and I can't.

**Comment by bvaughn** [comment]
Looks like it's being triggered by the `pointer-events` style `PanelGroup` is applying to `Panel`s when a resize is "active":
https://github.com/bvaughn/react-resizable-panels/blob/dffc160ecf9c917701f3eec043629736b5e2eb8d/packages/react-resizable-panels/src/PanelGroup.ts#L294-L296

**Comment by bvaughn** [comment]
Fix published in 0.0.36

Verified the fix by updating your Code Sandbox:
https://codesandbox.io/s/gallant-lewin-y23gcc?file=/package.json

**Comment by bvaughn** [comment]
You're welcome! Thanks for the Code Sandbox repro 😄
