### ISSUE TITLE
How to collapse the panel to its minSize

### ISSUE THREAD

**Issue by spa5k** [bvaughn/react-resizable-panels#97]
Something like `panel.collapse` but having option to only change the size to its minSize

**Comment by bvaughn** [comment]
I assume you're looking for the imperative API:
https://react-resizable-panels.vercel.app/examples/imperative-api

You can call:
```jsx
panelRef.current.resize(10); // Or whatever the min size is
```

**Comment by bvaughn** [comment]
If you update to 0.0.52, `Panel` supports a new `collapsedSize` prop that could be used for this. See it in action here:
https://react-resizable-panels.vercel.app/examples/collapsible
