### ISSUE TITLE
Absence of DOCTYPE in the website causes panel to become full viewport height

### ISSUE THREAD

**Issue by mohsinulhaq** [bvaughn/react-resizable-panels#99]
Hi Brian! Thanks for the library. Super helpful!

I was trying out the panels today and found that my panels were not taking the total available height by default like on the website.
I thought maybe the website is adding some global CSS making the body to be full height.

So I isolated the minimal horizontal example code with the index.html [here](https://react-resizable-panels.surge.sh) and to my surprise, it somehow was still full height. But when I try to use the component with exact same styles in Codesandbox or in CRA, it was still shrunk as you can see [here](https://y6yhjv.csb.app).

<img width="750" alt="image" src="https://user-images.githubusercontent.com/7688231/216666885-dfca635e-1044-4d03-8719-033dea823a5e.png">

So I asked around and [found](https://stackoverflow.com/a/75338864/3734818) that it's happening because the example website doesn't include a DOCTYPE [here](https://github.com/bvaughn/react-resizable-panels/blob/main/packages/react-resizable-panels-website/index.html#L1), leading to the browser reverting to [Quirks mode](https://developer.mozilla.org/en-US/docs/Web/HTML/Quirks_Mode_and_Standards_Mode).

I could add the DOCTYPE, but I am not sure how I can then cleanly make the panels take up all the available height without making use of things like `vh` on the body and the like. If you have an idea, I could raise a PR with that change.

Thanks! :)

**Comment by bvaughn** [comment]
Hey @mohsinulhaq!

I'm not sure I understand exactly what you're proposing here. The project website isn't meant to be cloned as used as-is. It's just a documentation site with some examples embedded (none of which are full screen).

If you want _your own website_ to use this component and be full screened then you can use the technique you're suggesting or you could use viewport units (`vw`/`vh`) 😄

**Comment by mohsinulhaq** [comment]
@bvaughn I am proposing that we add that DOCTYPE to the website, without which the browser turns to quirks mode, which as per the [docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Quirks_Mode_and_Standards_Mode#:~:text=In%20quirks%20mode%2C%20layout%20emulates%20behavior%20in%20Navigator%204%20and%20Internet%20Explorer%205), says that it is a compatibility mode for layout built for IE 5 and others.

So to add the DOCTYPE would mean making the app work in modern HTML 5 mode, which is used by all of the internet.
And this would also help showcase the user's responsibility of expanding the panel by giving explicit height to the panel containers even more clearly.

**Comment by bvaughn** [comment]
> So to add the DOCTYPE would mean making the app work in modern HTML 5 mode, which is used by all of the internet.

The docs demo site already works though, doesn't it? I think you're talking about _your_ app (which you created by cloning this repo?) I'm still not sure I understand 😅  Sorry

**Comment by mohsinulhaq** [comment]
> The docs demo site already works though

It works because you are relying on a legacy browser mode by forcing it to be in "Navigator 4/Internet Explorer 5" mode.
Which I am sure almost none of your users would be using.

So my suggestion is to switch to modern HTML5 mode in your website in order to have better parity with the environment your users use.

Here's a StackOverflow post to help better understand the issue: https://stackoverflow.com/a/75338864/3734818

**Comment by bvaughn** [comment]
Sorry, it’s not that I don’t understand the issue you’re describing. I do. I just don’t understand why it matters for the demo site.

The demo site works because I’m not making use of any features that differ between quirks and compatibility mode.

Honestly, I don’t really object if you want to submit a PR the adds a doctype tag- that’s fine. I just wouldn’t expect it to change anything in any observable way for the demo site, I don’t think.

**Comment by mohsinulhaq** [comment]
@bvaughn you are right. This won't change anything on the website. I have attached a screen recording to showcase why I was confused by the website compared to the usage in my app. The second tab contains the same website, but with DOCTYPE added.
Would you like me to raise a PR with the DOCTYPE?

https://user-images.githubusercontent.com/7688231/216996360-1049df07-2dea-435d-afcb-da97d8cd4962.mp4

**Comment by bvaughn** [comment]
Right. Understood. The demo site isn’t meant to be cloned as a starter though. It’s just for documentation purposes.

I don’t care one way or another regarding the PR 😃 If you’d like to submit one bc you think it might be helpful to others, I’m okay merging it.
